In [2]:
import pandas as pd 
import numpy as np

In [5]:
ds = pd.Series([10,20,30,40,50], index=['h','a','r','s','h'],dtype='float',name='harsh')
print(ds)

h    10.0
a    20.0
r    30.0
s    40.0
h    50.0
Name: harsh, dtype: float64

In [6]:
ds = pd.Series((10,20,30,40,50), index=['h','a','r','s','h'],dtype='float',name='harsh')
print(ds)

h    10.0
a    20.0
r    30.0
s    40.0
h    50.0
Name: harsh, dtype: float64

In [9]:
d = {1:"one",2:"two",3:"three",4:"four",5:"five"}
ds = pd.Series(d,name='harsh')
print(ds)

1      one
2      two
3    three
4     four
5     five
Name: harsh, dtype: object

In [10]:
a = np.array([10,20,30,40,50])
ds = pd.Series(a, index=['h','a','r','s','h'],dtype='float',name='harsh')
print(ds)

h    10.0
a    20.0
r    30.0
s    40.0
h    50.0
Name: harsh, dtype: float64

In [7]:
ds = pd.DataFrame([['h','a','r','s','h'],
                          [10,20,30,40,50],
                          [1,2,3,4,5]],columns=['a','b','c','d','e'])
print(ds)

    a   b   c   d   e
0   h   a   r   s   h
1  10  20  30  40  50
2   1   2   3   4   5

In [9]:
ds = pd.DataFrame({'name':['v','h','a'],
                 'mark' :[9.8,10,11],
                 'cgpa':[10,10,9.6]},index=['A','B','C'])
print(ds)

  name  mark  cgpa
A    v   9.8  10.0
B    h  10.0  10.0
C    a  11.0   9.6

In [35]:
df = pd.read_csv('train.csv')
print(df.index)
print(df.columns)
print(df.size)
print(df.shape)
print(df.values)
print(df.dtypes)
print(df.ndim)
df.set_index('Name')
df = df.reset_index()

RangeIndex(start=0, stop=891, step=1)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
10692
(891, 12)
[[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']]
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
2

In [59]:
df1 = pd.DataFrame({'name':['A','B','c'],
                   'mark':[10,20,30],
                   'cgpi':[1,2,3]},
                   index=['v','h','a'],
                   columns= ['name','mark','cgpi'])
df1.set_index('name',drop=True)
print(df1)
df.reset_index
print(df)

  name  mark  cgpi
v    A    10     1
h    B    20     2
a    c    30     3
     index  PassengerId  Survived  Pclass  \
0        0            1         0       3
1        1            2         1       1
2        2            3         1       3
3        3            4         1       1
4        4            5         0       3
..     ...          ...       ...     ...
886    886          887         0       2
887    887          888         1       1
888    888          889         0       3
889    889          890         1       1
890    890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 13 columns]

In [52]:
df1.set_index('name',drop=False)

     name  mark  cgpi index columns
name
A       A    10     1     v       p
B       B    20     2     h       q
c       c    30     3     a       r

In [69]:
df['Name']
print(type(df[['Name','Pclass']]))

<class 'pandas.core.frame.DataFrame'>

In [71]:
df.iloc[2,3]

3

In [72]:
df.iloc[2]

index                               2
PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                                26
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [73]:
df.iloc[2,]

index                               2
PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                                26
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [76]:
df.iloc[1:10,2:5]

   Survived  Pclass                                               Name
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry
5         0       3                                   Moran, Mr. James
6         0       1                            McCarthy, Mr. Timothy J
7         0       3                     Palsson, Master. Gosta Leonard
8         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9         1       2                Nasser, Mrs. Nicholas (Adele Achem)

In [78]:
df.iloc[1:0]

Empty DataFrame
Columns: [index, PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [90]:
df.loc['Heikkinen, Miss. Laina':'Saundercock, Mr. William Henry','PassengerId':'Age']

,PassengerId,Survived,Pclass,Sex,Age
Name,,,,,
"Heikkinen, Miss. Laina",3,1,3,female,26.0
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0
"Allen, Mr. William Henry",5,0,3,male,35.0
"Moran, Mr. James",6,0,3,male,NaN
"McCarthy, Mr. Timothy J",7,0,1,male,54.0
"Palsson, Master. Gosta Leonard",8,0,3,male,2.0
"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,1,3,female,27.0
"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0
"Sandstrom, Miss. Marguerite Rut",11,1,3,female,4.0
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0
"Saundercock, Mr. William Henry",13,0,3,male,20.0

In [97]:
df2 = pd.DataFrame([[10,40,70],
                    [20,50,80],
                    [30,60,90]],
                   index=['a','b','c'],
                   columns= ['p','q','r'])
print(df2)
df2.loc['b']

    p   q   r
a  10  40  70
b  20  50  80
c  30  60  90

p    20
q    50
r    80
Name: b, dtype: int64

In [98]:
df2.loc['b','q']

50

In [103]:
df2.loc['a':,'r']

a    70
b    80
c    90
Name: r, dtype: int64

In [106]:
df2.loc['b','q']=100
print(df2)

    p    q   r
a  10   40  70
b  20  100  80
c  30   60  90

In [108]:
df2['d']=df2['p']*df2['q']
print(df2)

    p    q   r     d
a  10   40  70   400
b  20  100  80  2000
c  30   60  90  1800

In [110]:
df2.loc['a':'c','p':'r']=7
print(df2)

   p  q  r     d
a  7  7  7   400
b  7  7  7  2000
c  7  7  7  1800

In [3]:
import seaborn as sns

ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.