In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame(np.random.randint(1,100,(8,5)),columns=['A','B','C','D','E'])
print(df)
print(df.shape)
print(df.size)
print(df.ndim)

    A   B   C   D   E
0  50   3  20  81   9
1  67  10  21  98  43
2  27  32  89  42  52
3  54  63  93  73   9
4  25  27  94  42  24
5  37  96  24   6  49
6  74   6  76  31  68
7  91  23   6  58  53
(8, 5)
40
2

In [5]:
print(df.shape)

(8, 5)

In [6]:
print(df.size)

40

In [7]:
print(df.ndim)

2

In [9]:
df['sum']=df['A']+df['B']+df['C']+df['D']+df['E']
print(df['sum'])

0    163
1    239
2    242
3    292
4    212
5    212
6    255
7    231
Name: sum, dtype: int32

In [10]:
df.iloc[5,2]=70
print(df)

    A   B   C   D   E  sum
0  50   3  20  81   9  163
1  67  10  21  98  43  239
2  27  32  89  42  52  242
3  54  63  93  73   9  292
4  25  27  94  42  24  212
5  37  96  70   6  49  212
6  74   6  76  31  68  255
7  91  23   6  58  53  231

In [12]:
print(df.loc[2:7,'B':'D'])

    B   C   D
2  32  89  42
3  63  93  73
4  27  94  42
5  96  70   6
6   6  76  31
7  23   6  58

In [13]:
df.loc[10]=[70,20,50,30,20,200]
print(df)

     A   B   C   D   E  sum
0   50   3  20  81   9  163
1   67  10  21  98  43  239
2   27  32  89  42  52  242
3   54  63  93  73   9  292
4   25  27  94  42  24  212
5   37  96  70   6  49  212
6   74   6  76  31  68  255
7   91  23   6  58  53  231
10  70  20  50  30  20  200

In [19]:
df1 = pd.DataFrame(np.random.randint(1,100,(5,4)),columns=['CourseID','CourseName','Credits','Faculty'])
print(df1)

   CourseID  CourseName  Credits  Faculty
0        85          96       87       37
1        26          11       84       11
2        77           2       90       69
3        60          50       58       50
4         9          45       48       53

In [20]:
df1 = df1.set_index('CourseID')
print(df1)

          CourseName  Credits  Faculty
CourseID
85                96       87       37
26                11       84       11
77                 2       90       69
60                50       58       50
9                 45       48       53

In [23]:
df1['Semester']=1
print(df1)

          CourseName  Credits  Faculty  Semester
CourseID
85                96       87       37         1
26                11       84       11         1
77                 2       90       69         1
60                50       58       50         1
9                 45       48       53         1

In [24]:
df1.iloc[1,1]=7
print(df1)

          CourseName  Credits  Faculty  Semester
CourseID
85                96       87       37         1
26                11        7       11         1
77                 2       90       69         1
60                50       58       50         1
9                 45       48       53         1

In [26]:
df1.loc['C6']=[1,44,55,2]
print(df1)

          CourseName  Credits  Faculty  Semester
CourseID
85                96       87       37         1
26                11        7       11         1
77                 2       90       69         1
60                50       58       50         1
9                 45       48       53         1
C6                 1       44       55         2

In [3]:
df2 = pd.read_csv('train.csv')
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df2.head() # Default is 5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df2.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [8]:
df2.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
df2.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0,NaN,S

In [12]:
df2.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
427,428,1,2,"Phillips, Miss. Kate Florence (""Mrs Kate Louis...",female,19.00,0,0,250655,26.0000,NaN,S
778,779,0,3,"Kilgannon, Mr. Thomas J",male,NaN,0,0,36865,7.7375,NaN,Q
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.00,0,1,250644,19.5000,NaN,S
321,322,0,3,"Danoff, Mr. Yoto",male,27.00,0,0,349219,7.8958,NaN,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
388,389,0,3,"Sadlier, Mr. Matthew",male,NaN,0,0,367655,7.7292,NaN,Q
254,255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.00,0,2,370129,20.2125,NaN,S
583,584,0,1,"Ross, Mr. John Hugo",male,36.00,0,0,13049,40.1250,A10,C
507,508,1,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [16]:
df2.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [18]:
df2.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Zabour, Miss. Thamine",male,NaN,NaN,NaN,1601,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [21]:
df2.describe(include='object')

                         Name   Sex Ticket Cabin Embarked
count                     891   891    891   204      889
unique                    891     2    681   147        3
top     Zabour, Miss. Thamine  male   1601    G6        S
freq                        1   577      7     4      644

In [22]:
df2.describe(exclude='integer')

,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
count,891,891,714.000000,891,891.000000,204,889
unique,891,2,NaN,681,NaN,147,3
top,"Zabour, Miss. Thamine",male,NaN,1601,NaN,G6,S
freq,1,577,NaN,7,NaN,4,644
mean,NaN,NaN,29.699118,NaN,32.204208,NaN,NaN
std,NaN,NaN,14.526497,NaN,49.693429,NaN,NaN
min,NaN,NaN,0.420000,NaN,0.000000,NaN,NaN
25%,NaN,NaN,20.125000,NaN,7.910400,NaN,NaN
50%,NaN,NaN,28.000000,NaN,14.454200,NaN,NaN
75%,NaN,NaN,38.000000,NaN,31.000000,NaN,NaN
max,NaN,NaN,80.000000,NaN,512.329200,NaN,NaN

In [24]:
df2.describe(percentiles=[0.2,0.3,0.8,0.9])

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
20%,179.000000,0.000000,1.000000,19.000000,0.000000,0.000000,7.854200
30%,268.000000,0.000000,2.000000,22.000000,0.000000,0.000000,8.050000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
80%,713.000000,1.000000,3.000000,41.000000,1.000000,1.000000,39.687500
90%,802.000000,1.000000,3.000000,50.000000,1.000000,2.000000,77.958300
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [25]:
df2.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [29]:
type(df2['Pclass'])

pandas.core.series.Series

In [30]:
df2.Sex.unique()

array(['male', 'female'], dtype=object)

In [32]:
df2.Pclass.unique()

array([3, 1, 2], dtype=int64)

In [34]:
df2.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [37]:
df2.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [38]:
df2.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [39]:
df2.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [42]:
df2[df2['Survived']==1]['Sex'].value_counts()

female    233
male      109
Name: Sex, dtype: int64

In [45]:
df2['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [47]:
df2.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [60]:
data=pd.DataFrame([[1,2,3,np.nan],[4,np.nan,5,np.nan],[7,8,9,10],[1,np.nan,3,4],[np.nan,np.nan,np.nan,np.nan]],columns=['A','B','C','D'])
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

In [56]:
data.dropna(how='all')

     0    1    2     3
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [58]:
data.dropna(axis=0,how='any')

     0    1    2     3
2  7.0  8.0  9.0  10.0

In [59]:
data.dropna(axis=1,how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [64]:
data.dropna(axis=0,how='any',subset=['D'])

     A    B    C     D
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [67]:
data.dropna(axis=0,how='all',subset=['D','B'])

     A    B    C     D
0  1.0  2.0  3.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [69]:
data.dropna(thresh=3)

     A    B    C     D
0  1.0  2.0  3.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0

In [71]:
df2.dropna(subset=['Cabin'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [72]:
df2.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [73]:
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  NaN  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  NaN  3.0   4.0
4  NaN  NaN  NaN   NaN

In [74]:
data.fillna(data.mean())

      A    B    C     D
0  1.00  2.0  3.0   7.0
1  4.00  5.0  5.0   7.0
2  7.00  8.0  9.0  10.0
3  1.00  5.0  3.0   4.0
4  3.25  5.0  5.0   7.0

In [76]:
data['B']=data['B'].fillna(data['B'].median())
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  5.0  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  5.0  3.0   4.0
4  NaN  5.0  NaN   NaN

In [77]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [79]:
df2.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [83]:
df2['Age']=df2['Age'].fillna(df2['Age'].mean())
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [84]:
df2.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [90]:
df2['Embarked']=df2['Embarked'].fillna(df2['Embarked'].mode()[0])

In [91]:
df2.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [92]:
data

     A    B    C     D
0  1.0  2.0  3.0   NaN
1  4.0  5.0  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  5.0  3.0   4.0
4  NaN  5.0  NaN   NaN

In [93]:
data.drop(0)

     A    B    C     D
1  4.0  5.0  5.0   NaN
2  7.0  8.0  9.0  10.0
3  1.0  5.0  3.0   4.0
4  NaN  5.0  NaN   NaN

In [94]:
data.drop('D',axis=1)

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  5.0
2  7.0  8.0  9.0
3  1.0  5.0  3.0
4  NaN  5.0  NaN

In [103]:
l=df2[df2['Sex']=='female'].index

In [104]:
df2.drop(l)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.000000,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [105]:
ds=pd.DataFrame([[1,1,2,3],[2,1,1,3],[1,1,2,3],[2,1,1,3],[1,1,2,2]],index=[7,8,9,10,11],columns=['p','q','r','s'])
ds

    p  q  r  s
7   1  1  2  3
8   2  1  1  3
9   1  1  2  3
10  2  1  1  3
11  1  1  2  2

In [106]:
ds.duplicated()

7     False
8     False
9      True
10     True
11    False
dtype: bool

In [107]:
ds.duplicated().sum()

2

In [108]:
ds.duplicated(subset=['p'])

7     False
8     False
9      True
10     True
11     True
dtype: bool

In [109]:
ds.drop_duplicates()

    p  q  r  s
7   1  1  2  3
8   2  1  1  3
11  1  1  2  2

In [110]:
ds.drop_duplicates(keep='last')

    p  q  r  s
9   1  1  2  3
10  2  1  1  3
11  1  1  2  2

In [111]:
ds.drop_duplicates(keep='first')

    p  q  r  s
7   1  1  2  3
8   2  1  1  3
11  1  1  2  2

In [112]:
ds.drop_duplicates(subset=['p'])

   p  q  r  s
7  1  1  2  3
8  2  1  1  3