Using Open Weather Map API, generate current air pollution data for
Ahmedabad and extract detail of aqi.

In [8]:
import requests
API_KEY='fdde21fb845fdaebec120c217b545b99'
LAT = 23.0225
LON = 72.5714
url = (
    f"https://api.openweathermap.org/data/2.5/air_pollution"
    f"?lat={LAT}&lon={LON}&appid={API_KEY}"
)

In [9]:
response = requests.get(url)
response.raise_for_status()

data = response.json()

In [10]:
data

{'coord': {'lon': 72.5714, 'lat': 23.0225},
 'list': [{'main': {'aqi': 1},
   'components': {'co': 91.66,
    'no': 0,
    'no2': 2.04,
    'o3': 46.75,
    'so2': 1.59,
    'pm2_5': 3.61,
    'pm10': 11.32,
    'nh3': 5.78},
   'dt': 1781626399}]}

In [11]:
aqi = data['list'][0]['main']['aqi']
components = data['list'][0]['components']

In [12]:
aqi,components

(1,
 {'co': 91.66,
  'no': 0,
  'no2': 2.04,
  'o3': 46.75,
  'so2': 1.59,
  'pm2_5': 3.61,
  'pm10': 11.32,
  'nh3': 5.78})

In [13]:
aqi_labels = {
    1: "Good",
    2: "Fair",
    3: "Moderate",
    4: "Poor",
    5: "Very Poor"
}
print(f"AQI : {aqi} ({aqi_labels.get(aqi,'Unknown')})")
print("Pollutants ")
for pollutant,value in components.items() :
    print(f"{pollutant.upper():<6} : {value}")

AQI : 1 (Good)
Pollutants
CO     : 91.66
NO     : 0
NO2    : 2.04
O3     : 46.75
SO2    : 1.59
PM2_5  : 3.61
PM10   : 11.32
NH3    : 5.78

370.  Using the Open Weather Map API, generate a 3 Hourly 5 Days weather forecast for Ahmedabad with all details in JSON format.
Note: Request for all the data via API in metric units.

In [17]:
import requests
import json
url = (
    "https://api.openweathermap.org/data/2.5/forecast"
    "?q=Ahmedabad,IN"
    "&units=metric"
    f"&appid={API_KEY}"
)

response=requests.get(url)
data = response.json()
print(json.dumps(data,indent=4))

{
    "cod": "200",
    "message": 0,
    "cnt": 40,
    "list": [
        {
            "dt": 1781632800,
            "main": {
                "temp": 34,
                "feels_like": 37.42,
                "temp_min": 32.32,
                "temp_max": 34,
                "pressure": 1005,
                "sea_level": 1005,
                "grnd_level": 1001,
                "humidity": 47,
                "temp_kf": 1.68
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n"
                }
            ],
            "clouds": {
                "all": 38
            },
            "wind": {
                "speed": 6.66,
                "deg": 276,
                "gust": 9.11
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-16 18:00:00"
        },
        {
            "dt": 1781643600,
            "main": {
                "temp": 32.67,
                "feels_like": 35.63,
                "temp_min": 31.59,
                "temp_max": 32.67,
                "pressure": 1006,
                "sea_level": 1006,
                "grnd_level": 1000,
                "humidity": 50,
                "temp_kf": 1.08
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n"
                }
            ],
            "clouds": {
                "all": 11
            },
            "wind": {
                "speed": 5.03,
                "deg": 266,
                "gust": 7.01
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-16 21:00:00"
        },
        {
            "dt": 1781654400,
            "main": {
                "temp": 30.43,
                "feels_like": 33.03,
                "temp_min": 30.43,
                "temp_max": 30.43,
                "pressure": 1006,
                "sea_level": 1006,
                "grnd_level": 1001,
                "humidity": 57,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 1
            },
            "wind": {
                "speed": 3.81,
                "deg": 255,
                "gust": 5.66
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-17 00:00:00"
        },
        {
            "dt": 1781665200,
            "main": {
                "temp": 32.16,
                "feels_like": 34.42,
                "temp_min": 32.16,
                "temp_max": 32.16,
                "pressure": 1008,
                "sea_level": 1008,
                "grnd_level": 1003,
                "humidity": 49,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.14,
                "deg": 238,
                "gust": 5.96
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-17 03:00:00"
        },
        {
            "dt": 1781676000,
            "main": {
                "temp": 36.35,
                "feels_like": 37.84,
                "temp_min": 36.35,
                "temp_max": 36.35,
                "pressure": 1007,
                "sea_level": 1007,
                "grnd_level": 1002,
                "humidity": 34,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.94,
                "deg": 235,
                "gust": 6.63
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-17 06:00:00"
        },
        {
            "dt": 1781686800,
            "main": {
                "temp": 39.8,
                "feels_like": 41.12,
                "temp_min": 39.8,
                "temp_max": 39.8,
                "pressure": 1004,
                "sea_level": 1004,
                "grnd_level": 998,
                "humidity": 26,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.64,
                "deg": 236,
                "gust": 6.31
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-17 09:00:00"
        },
        {
            "dt": 1781697600,
            "main": {
                "temp": 39.6,
                "feels_like": 41.16,
                "temp_min": 39.6,
                "temp_max": 39.6,
                "pressure": 1002,
                "sea_level": 1002,
                "grnd_level": 997,
                "humidity": 27,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 2
            },
            "wind": {
                "speed": 7.64,
                "deg": 220,
                "gust": 8.23
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-17 12:00:00"
        },
        {
            "dt": 1781708400,
            "main": {
                "temp": 35.82,
                "feels_like": 38.45,
                "temp_min": 35.82,
                "temp_max": 35.82,
                "pressure": 1004,
                "sea_level": 1004,
                "grnd_level": 999,
                "humidity": 39,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n"
                }
            ],
            "clouds": {
                "all": 90
            },
            "wind": {
                "speed": 1.98,
                "deg": 294,
                "gust": 3.19
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-17 15:00:00"
        },
        {
            "dt": 1781719200,
            "main": {
                "temp": 31.88,
                "feels_like": 34.88,
                "temp_min": 31.88,
                "temp_max": 31.88,
                "pressure": 1006,
                "sea_level": 1006,
                "grnd_level": 1001,
                "humidity": 53,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n"
                }
            ],
            "clouds": {
                "all": 85
            },
            "wind": {
                "speed": 5.75,
                "deg": 276,
                "gust": 9.32
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-17 18:00:00"
        },
        {
            "dt": 1781730000,
            "main": {
                "temp": 31.06,
                "feels_like": 33.13,
                "temp_min": 31.06,
                "temp_max": 31.06,
                "pressure": 1006,
                "sea_level": 1006,
                "grnd_level": 1000,
                "humidity": 52,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.25,
                "deg": 234,
                "gust": 6.91
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-17 21:00:00"
        },
        {
            "dt": 1781740800,
            "main": {
                "temp": 29.7,
                "feels_like": 31.91,
                "temp_min": 29.7,
                "temp_max": 29.7,
                "pressure": 1007,
                "sea_level": 1007,
                "grnd_level": 1001,
                "humidity": 58,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.16,
                "deg": 221,
                "gust": 6.87
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-18 00:00:00"
        },
        {
            "dt": 1781751600,
            "main": {
                "temp": 31.24,
                "feels_like": 33.66,
                "temp_min": 31.24,
                "temp_max": 31.24,
                "pressure": 1008,
                "sea_level": 1008,
                "grnd_level": 1003,
                "humidity": 53,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d"
                }
            ],
            "clouds": {
                "all": 12
            },
            "wind": {
                "speed": 5.79,
                "deg": 236,
                "gust": 6.87
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-18 03:00:00"
        },
        {
            "dt": 1781762400,
            "main": {
                "temp": 36.05,
                "feels_like": 37.61,
                "temp_min": 36.05,
                "temp_max": 36.05,
                "pressure": 1007,
                "sea_level": 1007,
                "grnd_level": 1001,
                "humidity": 35,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 10
            },
            "wind": {
                "speed": 5.87,
                "deg": 230,
                "gust": 6.87
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-18 06:00:00"
        },
        {
            "dt": 1781773200,
            "main": {
                "temp": 39.58,
                "feels_like": 40.04,
                "temp_min": 39.58,
                "temp_max": 39.58,
                "pressure": 1003,
                "sea_level": 1003,
                "grnd_level": 998,
                "humidity": 24,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.81,
                "deg": 241,
                "gust": 7.05
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-18 09:00:00"
        },
        {
            "dt": 1781784000,
            "main": {
                "temp": 39.49,
                "feels_like": 40.24,
                "temp_min": 39.49,
                "temp_max": 39.49,
                "pressure": 1002,
                "sea_level": 1002,
                "grnd_level": 997,
                "humidity": 25,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 6
            },
            "wind": {
                "speed": 7.08,
                "deg": 244,
                "gust": 7
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-18 12:00:00"
        },
        {
            "dt": 1781794800,
            "main": {
                "temp": 33.72,
                "feels_like": 36.27,
                "temp_min": 33.72,
                "temp_max": 33.72,
                "pressure": 1005,
                "sea_level": 1005,
                "grnd_level": 1000,
                "humidity": 45,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n"
                }
            ],
            "clouds": {
                "all": 75
            },
            "wind": {
                "speed": 3.11,
                "deg": 217,
                "gust": 4.57
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-18 15:00:00"
        },
        {
            "dt": 1781805600,
            "main": {
                "temp": 31.78,
                "feels_like": 34.44,
                "temp_min": 31.78,
                "temp_max": 31.78,
                "pressure": 1006,
                "sea_level": 1006,
                "grnd_level": 1000,
                "humidity": 52,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n"
                }
            ],
            "clouds": {
                "all": 41
            },
            "wind": {
                "speed": 5.36,
                "deg": 283,
                "gust": 8.27
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-18 18:00:00"
        },
        {
            "dt": 1781816400,
            "main": {
                "temp": 30.73,
                "feels_like": 32.76,
                "temp_min": 30.73,
                "temp_max": 30.73,
                "pressure": 1005,
                "sea_level": 1005,
                "grnd_level": 1000,
                "humidity": 53,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.71,
                "deg": 238,
                "gust": 7.27
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-18 21:00:00"
        },
        {
            "dt": 1781827200,
            "main": {
                "temp": 29.59,
                "feels_like": 31.22,
                "temp_min": 29.59,
                "temp_max": 29.59,
                "pressure": 1006,
                "sea_level": 1006,
                "grnd_level": 1000,
                "humidity": 55,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.17,
                "deg": 227,
                "gust": 7.81
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-06-19 00:00:00"
        },
        {
            "dt": 1781838000,
            "main": {
                "temp": 31.44,
                "feels_like": 32.94,
                "temp_min": 31.44,
                "temp_max": 31.44,
                "pressure": 1007,
                "sea_level": 1007,
                "grnd_level": 1001,
                "humidity": 48,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 1
            },
            "wind": {
                "speed": 6.01,
                "deg": 243,
                "gust": 7.34
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-06-19 03:00:00"
        },
        {
            "dt": 1781848800,
            "main": {
                "temp": 36.33,
                "feels_like": 37.22,
                "temp_min": 36.33,
                "temp_max": 36.33,
                "pressure": 1006,
                "sea_level": 1006,
                "grnd_level": 1001,
                "humidity": 32,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",

371. Using the Open Weather Map API, find the location of ahmedabad

In [19]:
import requests
url = (
    "http://api.openweathermap.org/geo/1.0/direct"
    "?q=Ahmedabad,IN"
    f"&limit=1&appid={API_KEY}"
)

response = requests.get(url)
location = response.json()
location

[{'name': 'Ahmedabad',
  'local_names': {'ja': 'アフマダーバード',
   'he': 'אחמדאבאד',
   'hi': 'अहमदाबाद',
   'ta': 'அகமதாபாத்',
   'uk': 'Ахмедабад',
   'zh': '艾哈迈达巴德',
   'oc': 'Ahmadabad',
   'bn': 'আহমেদাবাদ',
   'ar': 'أحمد آباد',
   'ru': 'Ахмадабад',
   'ml': 'അഹമ്മദാബാദ്',
   'feature_name': 'Ahmedabad',
   'cs': 'Ahmadábád',
   'eo': 'Ahmadabado',
   'ur': 'احمد آباد',
   'pa': 'ਅਹਿਮਦਾਬਾਦ',
   'kn': 'ಅಹ್ಮದಾಬಾದ್',
   'te': 'అహ్మదాబాద్',
   'tt': 'Әхмәтабад',
   'en': 'Ahmedabad',
   'mr': 'अहमदाबाद',
   'gu': 'અમદાવાદ',
   'pl': 'Ahmadabad',
   'de': 'Ahmedabad',
   'ascii': 'Ahmedabad',
   'or': 'ଅହମଦାବାଦ',
   'ne': 'अहमदाबाद'},
  'lat': 23.0215374,
  'lon': 72.5800568,
  'country': 'IN',
  'state': 'Gujarat'}]

In [20]:
city = location[0]

print("City:", city["name"])
print("State:", city["state"])
print("Country:", city["country"])
print("Latitude:", city["lat"])
print("Longitude:", city["lon"])

City: Ahmedabad
State: Gujarat
Country: IN
Latitude: 23.0215374
Longitude: 72.5800568

372. Using the Open Weather Map API, find the wind_speed of ahmedabad

In [21]:

url = (
    "https://api.openweathermap.org/data/2.5/weather"
    "?q=Ahmedabad,IN"
    "&units=metric"
    f"&appid={API_KEY}"
)

response = requests.get(url)
data = response.json()

wind_speed = data["wind"]["speed"]
wind_direction = data["wind"]["deg"]

print("Wind Speed:", wind_speed, "m/s")
print("Wind Direction:", wind_direction, "°")

Wind Speed: 6.24 m/s
Wind Direction: 269 °

373. Using the Open Weather Map API, generate a 3 hourly 5 days weather forecast for Ahmedabad with details like minimum
temperature, maximum temperature, wind speed, humidity, and weather description. Display this data in the form of a Pandas
data frame with the column names being date_time, min_temp, max_temp, wind_speed, humidity, and weather_description.

In [23]:
import pandas as pd
url = (
    "https://api.openweathermap.org/data/2.5/forecast"
    "?q=Ahmedabad,IN"
    "&units=metric"
    f"&appid={API_KEY}"
)

# Fetch data
response = requests.get(url)
data = response.json()

# Create list to store forecast records
forecast_data = []

# Extract required details
for item in data["list"]:
    forecast_data.append({
        "date_time": item["dt_txt"],
        "min_temp": item["main"]["temp_min"],
        "max_temp": item["main"]["temp_max"],
        "wind_speed": item["wind"]["speed"],
        "humidity": item["main"]["humidity"],
        "weather_description": item["weather"][0]["description"]
    })

# Convert to Pandas DataFrame
df = pd.DataFrame(forecast_data)

# Display DataFrame
print(df)

# Optional: View first few rows
print("\nFirst 5 Forecast Records:")
print(df.head())

              date_time  min_temp  max_temp  wind_speed  humidity  \
0   2026-06-16 18:00:00     32.32     32.32        6.66        52
1   2026-06-16 21:00:00     31.59     32.08        5.03        53
2   2026-06-17 00:00:00     30.43     31.06        3.81        56
3   2026-06-17 03:00:00     32.16     32.16        5.14        49
4   2026-06-17 06:00:00     36.35     36.35        5.94        34
5   2026-06-17 09:00:00     39.80     39.80        5.64        26
6   2026-06-17 12:00:00     39.60     39.60        7.64        27
7   2026-06-17 15:00:00     35.82     35.82        1.98        39
8   2026-06-17 18:00:00     31.88     31.88        5.75        53
9   2026-06-17 21:00:00     31.06     31.06        5.25        52
10  2026-06-18 00:00:00     29.70     29.70        5.16        58
11  2026-06-18 03:00:00     31.24     31.24        5.79        53
12  2026-06-18 06:00:00     36.05     36.05        5.87        35
13  2026-06-18 09:00:00     39.58     39.58        5.81        24
14  2026-06-18 12:00:00     39.49     39.49        7.08        25
15  2026-06-18 15:00:00     33.72     33.72        3.11        45
16  2026-06-18 18:00:00     31.78     31.78        5.36        52
17  2026-06-18 21:00:00     30.73     30.73        5.71        53
18  2026-06-19 00:00:00     29.59     29.59        5.17        55
19  2026-06-19 03:00:00     31.44     31.44        6.01        48
20  2026-06-19 06:00:00     36.33     36.33        5.31        32
21  2026-06-19 09:00:00     39.99     39.99        5.93        24
22  2026-06-19 12:00:00     38.87     38.87        8.51        28
23  2026-06-19 15:00:00     31.91     31.91        5.92        59
24  2026-06-19 18:00:00     32.20     32.20        1.71        56
25  2026-06-19 21:00:00     31.25     31.25        4.67        51
26  2026-06-20 00:00:00     29.67     29.67        4.98        61
27  2026-06-20 03:00:00     30.97     30.97        6.13        57
28  2026-06-20 06:00:00     36.10     36.10        6.34        34
29  2026-06-20 09:00:00     39.94     39.94        6.03        24
30  2026-06-20 12:00:00     39.86     39.86        7.09        26
31  2026-06-20 15:00:00     32.37     32.37        5.38        57
32  2026-06-20 18:00:00     32.17     32.17        5.30        53
33  2026-06-20 21:00:00     30.99     30.99        5.70        53
34  2026-06-21 00:00:00     29.07     29.07        5.18        62
35  2026-06-21 03:00:00     30.63     30.63        5.65        54
36  2026-06-21 06:00:00     35.75     35.75        5.48        34
37  2026-06-21 09:00:00     40.08     40.08        5.73        23
38  2026-06-21 12:00:00     40.25     40.25        7.10        23
39  2026-06-21 15:00:00     33.07     33.07        5.77        49

   weather_description
0     scattered clouds
1     scattered clouds
2           few clouds
3            clear sky
4            clear sky
5            clear sky
6            clear sky
7      overcast clouds
8      overcast clouds
9            clear sky
10           clear sky
11          few clouds
12           clear sky
13           clear sky
14           clear sky
15       broken clouds
16    scattered clouds
17           clear sky
18           clear sky
19           clear sky
20           clear sky
21           clear sky
22           clear sky
23           clear sky
24           clear sky
25          few clouds
26           clear sky
27           clear sky
28           clear sky
29           clear sky
30           clear sky
31           clear sky
32           clear sky
33           clear sky
34           clear sky
35           clear sky
36           clear sky
37           clear sky
38           clear sky
39           clear sky

First 5 Forecast Records:
             date_time  min_temp  max_temp  wind_speed  humidity  \
0  2026-06-16 18:00:00     32.32     32.32        6.66        52
1  2026-06-16 21:00:00     31.59     32.08        5.03        53
2  2026-06-17 00:00:00     30.43     31.06        3.81        56
3  2026-06-17 03:00:00     32.16     32.16        5.14        49
4  2026-06-17 06:00:00     36.35     36.35        5.94        34

  weather_description
0    scattered clouds
1    scattered clouds
2          few clouds
3           clear sky
4           clear sky

374. Write a Python program using beautiful soup to scrape all the news headlines in the div class “top news” from
https://indianexpress.com/

In [27]:
import requests
from bs4 import BeautifulSoup 
url = 'https://indianexpress.com/'
r = requests.get(url)
soup = BeautifulSoup(r.text,'html.parser')

In [47]:
top = soup.find_all('div',class_='topblockNews__featured')[0]
top.find_all('article',class_='topblockNews__featuredItem')[0].text

'IndiaIn PM Modi, Trump’s first face-to-face in 16 months, a handshake breaks iceThis was their first face-to-face encounter since their meeting at the White House in February 2025.'

375. Write a program for web scrapping using BeautifulSoup to scrape the following details from the given link and make a data
frame using that scraped data from
the page in a given link.
Link: https://www.politifact.com/factchecks
You will find 30 news articles with fact checks on this page. You need to scrape the following details from all the articles and
store that in a data frame. Statement of News, Date of News, Source of News.

In [87]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the webpage
url = "https://www.politifact.com/factchecks"

# Send HTTP request
headers = {
    "User-Agent": "Mozilla/5.0"
}
response = requests.get(url, headers=headers)

# Parse HTML content
soup = BeautifulSoup(response.content, "html.parser")

# Lists to store scraped data
statements = []
dates = []
sources = []

# Find all fact-check articles
articles = soup.find_all("article", class_="m-statement")

# Loop through each article
for article in articles:
    
    # Extract Statement of News
    statement = article.find("div", class_="m-statement__quote")
    if statement:
        statements.append(statement.get_text(strip=True))
    else:
        statements.append("N/A")
    
    # Extract Source of News
    source = article.find("a", class_="m-statement__name")
    if source:
        sources.append(source.get_text(strip=True))
    else:
        sources.append("N/A")
    
    # Extract Date of News
    date = article.find("div", class_="m-statement__desc")
    if date:
        # Example text: "stated on May 24, 2025 in..."
        dates.append(date.get_text(strip=True))
    else:
        dates.append("N/A")

# Create DataFrame
df = pd.DataFrame({
    "Statement of News": statements,
    "Date of News": dates,
    "Source of News": sources
})

# Display DataFrame
df

,Statement of News,Date of News,Source of News
0,“Michelle Obama is a man.”,"stated on June 14, 2026 in a UFC event at the ...",Josh Hokit
1,“If you live near one of these large data cent...,"stated on June 5, 2026 in an X post:",Elizabeth Warren
2,“No Republican wins in Nassau.”,"stated on May 22, 2026 in remarks in Suffern, ...",Donald Trump
3,Sen. Susan Collins votes “with Donald Trump 95...,"stated on June 9, 2026 in a primary night speech:",Graham Platner
4,The ongoing ballot counting in California mean...,"stated on June 7, 2026 in an interview on NBC'...",Donald Trump
5,Los Angeles mayoral candidate Spencer Pratt “g...,"stated on June 4, 2026 in X posts:",X posts
6,This video shows a June 2026 earthquake in the...,"stated on June 7, 2026 in an X post:",X posts
7,This image shows a person stuffing ballots int...,"stated on June 5, 2026 in social media posts:",Social Media
8,Los Angeles mayoral candidate Nithya Raman had...,"stated on June 7, 2026 in X posts:",X posts
9,Iowa Democratic U.S. Senate candidate Josh Tur...,"stated on June 2, 2026 in an ad:",Ashley Hinson
10,"""The number of New Yorkers who consume cannabi...","stated on April 2, 2026 in an interview with P...",John Kagia
11,"""Michigan has spent more than $2.5 billion on ...","stated on May 28, 2026 in a Democratic primary...",Mallory McMorrow
12,“Adam Hoffman abused a little boy” and Ken Pax...,"stated on May 28, 2026 in an X post:",James Talarico
13,Says his cognitive test results showed he has ...,"stated on May 31, 2026 in a Truth Social post:",Donald Trump
14,A video shows workers removing President Donal...,"stated on May 31, 2026 in social media posts:",Social Media
15,El presidente Donald Trump firmó una ley para ...,"stated on May 27, 2026 in una publicación en T...",TikTok posts
16,Democratic Texas U.S. Senate candidate James T...,"stated on May 27, 2026 in an ad:",Ken Paxton
17,Democratic Texas U.S. Senate candidate James T...,"stated on May 26, 2026 in a primary election v...",Ken Paxton
18,“The reason (people in Cuba) are forced to sur...,"stated on May 20, 2026 in an X post:",Marco Rubio
19,“President Trump’s tariffs are costing New Yor...,"stated on March 19, 2026 in a press release:",Kirsten Gillibrand
20,"""There's been numerous other occasions over th...","stated on May 18, 2026 in remarks at the White...",Donald Trump
21,“San Diego mosque shooters identified as trans...,"stated on May 19, 2026 in in social media posts:",Social Media
22,"Video shows U.S. Rep. Byron Donalds saying, “I...","stated on May 14, 2026 in X posts:",X posts
23,An American passenger on the cruise ship invol...,"stated on May 6, 2026 in an X post:",X posts
24,“Florida is the only state in the nation kicki...,"stated on April 29, 2026 in an X post:",Kathy Castor
25,"In 2020, “Amy Acton called off Ohio’s election...","stated on April 24, 2026 in an ad:",Vivek Ramaswamy
26,Imágenes muestran a personas “infectadas con H...,"stated on May 8, 2026 in una publicación en Ti...",TikTok posts
27,"“Today, there are more children sleeping in Ne...","stated on March 5, 2026 in a press release:",Christine Quinn
28,“The average IRS tax refund is up 11% compared...,"stated on March 31, 2026 in an X post:",Nicholas Langworthy
29,Gasoline prices have “come down very substanti...,"stated on May 7, 2026 in remarks to reporters:",Donald Trump

376. Write a program of web scrapping using BeautifulSoup to scrape the given data from the following link.
https://editorial.rottentomatoes.com/guide/popular-movies/
On the above link, you’ll find 30 Popular movies. Scrape the Movie Title and Rating of that particular movie and make a
Dataframe of the same.

In [108]:
import requests 
from bs4 import BeautifulSoup
import pandas as pd 
url = 'https://editorial.rottentomatoes.com/guide/popular-movies/'
response = requests.get(url)
soup = BeautifulSoup(response.content,'html.parser')
m = soup.find_all('div',class_='content-body')[0]
df = {
    'title' : [],
    'rating' : []
}
for i in (soup.find_all('div',class_='block-countdown rkv-block')) :
    df['title'].append(i.find('div',class_='meta-title-wrapper').text.strip().split('\n')[0])
    df['rating'].append(i.find('div',class_='meta-scores-wrapper').text.strip())
df = pd.DataFrame(df)
df

                                       title rating
0                                Scary Movie    23%
1                    Masters of the Universe    68%
2                                  Backrooms    88%
3                                  Obsession    94%
4                                      Hokum    90%
5                                   Pressure    86%
6       Star Wars: The Mandalorian and Grogu    62%
7                          Project Hail Mary    94%
8   The Amazing Digital Circus: The Last Act    - -
9                             Office Romance    48%
10                            Disclosure Day    81%
11                           The Breadwinner    20%
12                                   Michael    38%
13                      The Perfect Neighbor    99%
14                               In the Grey    49%
15                              Power Ballad    87%
16                                     Tuner    94%
17                                 Send Help    92%
18                                    Exit 8    93%
19                      The Sheep Detectives    95%
20                                 Iron Lung    59%
21                                   Hoppers    94%
22                              Ladies First    25%
23                               The Furious    97%
24                                 Passenger    48%
25               Remarkably Bright Creatures    84%
26                                   I Swear    97%
27                                      Apex    67%
28                           Dead Man's Wire    91%
29                                 Is God Is    97%

378. Write a Python program to retrieve all the paragraph tags from a given HTML document. html_doc = """
<html> <head>
<meta http-equiv="Content-Type" content="text/html;
charset=iso-8859-1">
<title>An example of HTML page</title> </head>
<body>
<h2>This is an example HTML page</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus
euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis.
Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed
pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis,
dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>
<p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from
w3resource.com</a></p>
<p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from
w3resource.com</a></p>
</body>
</html>
"""

In [119]:
import requests
from bs4 import BeautifulSoup
with open('document.html','r',encoding='utf-8') as f :
    res = f.read()
soup = BeautifulSoup(res,'html.parser')
for i in (soup.find_all('p')) :
    print(i.text)
p = len(soup.find_all('p'))
print(f"total p tags {p}")

print("First p tag")
print(soup.find('p'))

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus
euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis.
Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed
pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis,
dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.
Learn HTML from
w3resource.com
Learn CSS from
w3resource.com
total p tags 3
First p tag
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus
euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis.
Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed
pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis,
dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>

381. Write a Python program to find the length of the text of the first <h2> tag of a given html document html

In [122]:
print(len(soup.find('h2').text))

28

382  Write a Python program to find the text of the first <a> tag of a given html text.

In [124]:
print(soup.find('a').text)

Learn HTML from
w3resource.com

383. Write a Python program to interact with the following REST API:
https://reqres.in/api/users
The program should:
Send a POST request to create a new user.
Send JSON data containing name and job.
Include a custom Authorization header token.
Convert the API response to a Python dictionary(JSON)

387. Write a Python program to extract all the URLs from the webpage python.org that are nested within 'li'tags from

In [133]:
import requests 
from bs4 import BeautifulSoup

url = 'https://python.org/'
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
urls = []
for l in soup.find_all('li'):
    a = l.find('a')

    if a and a.has_attr('href'):
        urls.append(a['href'])
print("Total URLS ",len(urls))
print(urls)

Total URLS  163
['/', 'https://www.python.org/psf/', 'https://docs.python.org', 'https://pypi.org/', '/jobs/', '/community/', '#', 'javascript:;', 'javascript:;', 'javascript:;', '#', 'https://www.linkedin.com/company/python-software-foundation/', 'https://fosstodon.org/@ThePSF', '/community/irc/', 'https://twitter.com/ThePSF', '/about/', '/about/apps/', '/about/quotes/', '/about/gettingstarted/', '/about/help/', 'http://brochure.getpython.info/', '/downloads/', '/downloads/', '/downloads/source/', '/downloads/windows/', '/downloads/macos/', '/downloads/android/', '/download/other/', 'https://docs.python.org/3/license.html', '/download/alternatives', '/doc/', '/doc/', '/doc/av', 'https://wiki.python.org/moin/BeginnersGuide', 'https://docs.python.org/3/faq/', 'https://translations.python.org/', 'https://peps.python.org', 'https://wiki.python.org/moin/PythonBooks', '/doc/essays/', '/community/', '/community/diversity/', '/community/lists/', '/community/irc/', '/community/forums/', '/psf/annual-report/2024/', '/community/workshops/', '/community/sigs/', '/community/logos/', 'https://wiki.python.org/moin/', '/psf/conduct/', '/community/awards', '/psf/get-involved/', '/psf/community-stories/', '/success-stories/', '/success-stories/category/arts/', '/success-stories/category/business/', '/success-stories/category/education/', '/success-stories/category/engineering/', '/success-stories/category/government/', '/success-stories/category/scientific/', '/success-stories/category/software-development/', '/blogs/', '/blogs/', '/psf/newsletter/', 'http://pyfound.blogspot.com/', 'http://pycon.blogspot.com/', 'http://planetpython.org/', '/events/', '/events/python-events/', '/events/python-user-group/', '/events/python-events/past/', '/events/python-user-group/past/', 'https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event', '/shell/', 'http://docs.python.org/3/tutorial/introduction.html#using-python-as-a-calculator', '//docs.python.org/3/tutorial/introduction.html#lists', '//docs.python.org/3/tutorial/controlflow.html', '//docs.python.org/3/tutorial/controlflow.html#defining-functions', '//docs.python.org/3/tutorial/', 'https://blog.python.org/2026/06/python-3146-31314/', 'https://pyfound.blogspot.com/2026/06/psf-strategic-plan-2026-draft-open-for.html', 'https://pyfound.blogspot.com/2026/06/no-starch-press-humble-bundle-grab-deal.html', 'https://blog.python.org/2026/06/python-3150-beta-2/', 'https://pyfound.blogspot.com/2026/05/psf-welcomes-hudson-river-trading-hrt.html', '/events/python-user-group/2170/', '/events/python-events/2173/', '/events/python-events/2178/', '/events/python-events/2148/', '/events/python-events/2141/', 'https://www.djangoproject.com/', 'https://en.wikipedia.org/wiki/Tkinter', 'https://pytorch.org/', 'https://scipy.org/', 'https://buildbot.net/', 'https://docs.ansible.com/', '/about/', '/about/apps/', '/about/quotes/', '/about/gettingstarted/', '/about/help/', 'http://brochure.getpython.info/', '/downloads/', '/downloads/', '/downloads/source/', '/downloads/windows/', '/downloads/macos/', '/downloads/android/', '/download/other/', 'https://docs.python.org/3/license.html', '/download/alternatives', '/doc/', '/doc/', '/doc/av', 'https://wiki.python.org/moin/BeginnersGuide', 'https://docs.python.org/3/faq/', 'https://translations.python.org/', 'https://peps.python.org', 'https://wiki.python.org/moin/PythonBooks', '/doc/essays/', '/community/', '/community/diversity/', '/community/lists/', '/community/irc/', '/community/forums/', '/psf/annual-report/2024/', '/community/workshops/', '/community/sigs/', '/community/logos/', 'https://wiki.python.org/moin/', '/psf/conduct/', '/community/awards', '/psf/get-involved/', '/psf/community-stories/', '/success-stories/', '/success-stories/category/arts/', '/success-stories/category/business/', '/success-stories/category/education/', '/success-stories/category/engineering/', '/success-stories/category/government/', '/success-stories/category/scientific/', '/success-stories/category/software-development/', '/blogs/', '/blogs/', '/psf/newsletter/', 'http://pyfound.blogspot.com/', 'http://pycon.blogspot.com/', 'http://planetpython.org/', '/events/', '/events/python-events/', '/events/python-user-group/', '/events/python-events/past/', '/events/python-user-group/past/', 'https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event', '/dev/', 'https://devguide.python.org/', 'https://github.com/python/cpython/issues', 'https://mail.python.org/mailman/listinfo/python-dev', '/dev/core-mentorship/', '/dev/security/', '/about/help/', '/community/diversity/', 'https://github.com/python/pythondotorg/issues', 'https://status.python.org/']

386. Write a Python program to find all the h2 tags and list the first four from the webpage python.org.

In [138]:
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
h = []
for i in (soup.find_all('h1')):
     h.append(i.text)
h[:4]

['Intuitive Interpretation',
 'Compound Data Types',
 'All the Flow You’d Expect',
 'Functions Defined']

387. Find all the link tags and list the first ten from the webpage python.org

In [143]:
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
a = []
for i in soup.find_all('a'):
    a.append(i.text)
a[:10]

['Skip to content',
 '\n▼ Close\n                ',
 'Python',
 'PSF',
 'Docs',
 'PyPI',
 'Jobs',
 'Community',
 '\n▲ The Python Network\n                ',
 '']

388. Write a Python program to a list of all the h1, h2, h3 tags from the webpage python.org.

In [145]:
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
h1 = []
h2 = []
h3 = []
for i in (soup.find_all('h1')):
    h1.append(i)
for i in (soup.find_all('h2')):
    h2.append(i)
for i in (soup.find_all('h3')):
    h3.append(i)
h1,h2,h3

([<h1>Intuitive Interpretation</h1>,
  <h1>Compound Data Types</h1>,
  <h1>All the Flow You’d Expect</h1>,
  <h1>Functions Defined</h1>,
  <h1>Quick &amp; Easy to Learn</h1>],
 [<h2 class="widget-title"><span aria-hidden="true" class="icon-get-started"></span>Get Started</h2>,
  <h2 class="widget-title"><span aria-hidden="true" class="icon-download"></span>Download</h2>,
  <h2 class="widget-title"><span aria-hidden="true" class="icon-documentation"></span>Docs</h2>,
  <h2 class="widget-title"><span aria-hidden="true" class="icon-jobs"></span>Jobs</h2>,
  <h2 class="widget-title"><span aria-hidden="true" class="icon-news"></span>Latest News</h2>,
  <h2 class="widget-title"><span aria-hidden="true" class="icon-calendar"></span>Upcoming Events</h2>,
  <h2 class="widget-title"><span aria-hidden="true" class="icon-success-stories"></span>Success Stories</h2>,
  <h2 class="widget-title"><span aria-hidden="true" class="icon-python"></span>Use Python for…</h2>,
  <h2 class="widget-title">
  <span class="prompt">&gt;&gt;&gt;</span> <a href="/psf/">Python Software Foundation</a>
  </h2>],
 [])

389.  Write a Python program to extract all the text from a given web page python.org.

In [148]:
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
print(soup.text.strip())

Welcome to Python.org




















Notice: This page displays a fallback because interactive scripts did not run. Possible causes include disabled JavaScript or failure to load scripts or stylesheets.





Skip to content


▼ Close



Python


PSF


Docs


PyPI


Jobs


Community



▲ The Python Network










Donate

≡ Menu


Search This Site


                                    GO





A A

Smaller
Larger
Reset






Socialize

LinkedIn
Mastodon
Chat on IRC
Twitter










About

Applications
Quotes
Getting Started
Help
Python Brochure



Downloads

All releases
Source code
Windows
macOS
Android
Other Platforms
License
Alternative Implementations



Documentation

Docs
Audio/Visual Talks
Beginner's Guide
FAQ
Non-English Docs
PEP Index
Python Books
Python Essays



Community

Diversity
Mailing Lists
IRC
Forums
PSF Annual Impact Report
Python Conferences
Special Interest Groups
Python Logo
Python Wiki
Code of Conduct
Community Awards
Get Involved
Shared Stories



Success Stories

Arts
Business
Education
Engineering
Government
Scientific
Software Development



News

Python News
PSF Newsletter
PSF News
PyCon US News
News from the Community



Events

Python Events
User Group Events
Python Events Archive
User Group Events Archive
Submit an Event








>_
                        Launch Interactive Shell





# Simple arithmetic
>>> 1 / 2
0.5
>>> 2 ** 3
8
>>> 17 / 3  # true division returns a float
5.666666666666667
>>> 17 // 3  # floor division
5

Intuitive Interpretation
Calculations are simple with Python, and expression syntax is straightforward: the operators +, -, * and / work as expected; parentheses () can be used for grouping. More about simple math functions in Python 3.


# Python 3: List comprehensions
>>> fruits = ['Banana', 'Apple', 'Lime']
>>> loud_fruits = [fruit.upper() for fruit in fruits]
>>> print(loud_fruits)
['BANANA', 'APPLE', 'LIME']

# List and the enumerate function
>>> list(enumerate(fruits))
[(0, 'Banana'), (1, 'Apple'), (2, 'Lime')]

Compound Data Types
Lists (known as arrays in other languages) are one of the compound data types that Python understands. Lists can be indexed, sliced and manipulated with other built-in functions. More about lists in Python 3


# For loop on a list
>>> numbers = [2, 4, 6, 8]
>>> product = 1
>>> for number in numbers:
...    product = product * number
...
>>> print('The product is:', product)
The product is: 384

All the Flow You’d Expect
Python knows the usual control flow statements that other languages speak — if, for, while and range — with some of its own twists, of course. More control flow tools in Python 3


# Python 3: Fibonacci series up to n
>>> def fib(n):
>>>     a, b = 0, 1
>>>     while a < n:
>>>         print(a, end=' ')
>>>         a, b = b, a+b
>>>     print()
>>> fib(1000)
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987

Functions Defined
The core of extensible programming is defining functions. Python allows mandatory and optional arguments, keyword arguments, and even arbitrary argument lists. More about defining functions in Python 3


# Simple output (with Unicode)
>>> print("Hello, I'm Python!")
Hello, I'm Python!

# Input, assignment
>>> name = input('What is your name?\n')
>>> print(f'Hi, {name}.')
What is your name?
Python
Hi, Python.

Quick & Easy to Learn
Experienced programmers in any other language can pick up Python very quickly, and beginners find the clean syntax and indentation structure easy to learn. Whet your appetite with our Python 3 overview.





Python is a programming language that lets you work quickly and integrate systems more effectively. Learn More









Get Started
Whether you're new to programming or an experienced developer, it's easy to learn and use Python.
Start with our Beginner’s Guide


Download
Python source code and installers are available for download for all versions!
Latest: Python 3.14.6


Docs
Documentation for Python's standard library, along with tutorials and guides, are available online.
docs.python.org


Jobs
Looking for work or have a Python related position that you're trying to hire for? Our relaunched community-run job board is the place to go.
jobs.python.org





Latest News
More


2026-06-10
Python 3.14.6 and 3.13.14 are now available!

2026-06-04
PSF Strategic Plan 2026 Draft: Open for Community Feedback

2026-06-02
No Starch Press Humble Bundle: Grab a Deal and Support the PSF!

2026-06-02
Python 3.15.0 beta 2 is here!

2026-05-13
PSF Welcomes Hudson River Trading (HRT) as a Visionary Sponsor





Upcoming Events
More


2026-06-18
Python for (Almost) Everything

2026-06-19
PyCon Singapore 2026

2026-07-03
Python Norte 2026

2026-07-13
SciPy 2026

2026-07-13
EuroPython 2026







Success Stories
More


“We feel much better equipped now to handle the challenges. And if we run into an issue, we’ll come to Caktus to hammer it out," said Stephen Johnston, VP of Engineering, at Force Therapeutics.




A Startup Healthcare Tech Firm Is Now Poised for the Future by Caktus Group








Use Python for…
More

Web Development:
        Django, Pyramid, Bottle, Tornado, Flask, Litestar, FastAPI
GUI Development:
        tkInter, PyGObject, PyQt, PySide, Kivy, wxPython, DearPyGui
AI and Machine Learning:
        PyTorch, TensorFlow, scikit-learn, Transformers, Anthropic, LangChain
Scientific and Numeric:
        SciPy, Pandas, IPython
Software Development:
        Buildbot, Trac, Roundup
System Administration:
        Ansible, Salt, OpenStack, xonsh







>>> Python Software Foundation

The mission of the Python Software Foundation is to promote, protect, and advance the Python programming language, and to support and facilitate the growth of a diverse and international community of Python programmers. Learn more

Become a Member
Donate to the PSF









▲ Back to Top


About

Applications
Quotes
Getting Started
Help
Python Brochure



Downloads

All releases
Source code
Windows
macOS
Android
Other Platforms
License
Alternative Implementations



Documentation

Docs
Audio/Visual Talks
Beginner's Guide
FAQ
Non-English Docs
PEP Index
Python Books
Python Essays



Community

Diversity
Mailing Lists
IRC
Forums
PSF Annual Impact Report
Python Conferences
Special Interest Groups
Python Logo
Python Wiki
Code of Conduct
Community Awards
Get Involved
Shared Stories



Success Stories

Arts
Business
Education
Engineering
Government
Scientific
Software Development



News

Python News
PSF Newsletter
PSF News
PyCon US News
News from the Community



Events

Python Events
User Group Events
Python Events Archive
User Group Events Archive
Submit an Event



Contributing

Developer's Guide
Issue Tracker
python-dev list
Core Mentorship
Report a Security Issue



▲ Back to Top





Help & General Contact
Diversity Initiatives
Submit Website Bug

Status




Copyright ©2001-2026.
                             Python Software Foundation
                             Legal Statements
                             Privacy Notice

390. How to get the Daily News using Python. url='https://www.bbc.com/news'

In [154]:
url = 'https://www.bbc.com/news'
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
n = []
news = soup.find_all(['h2','h3'])
for i in news :
    n.append(i.text)
n

['UK investigating reports Russian warship fired warning shots near yacht in English Channel',
 'UK forces face operational cuts without more cash, defence chief warns',
 'India temporarily bans Telegram over exam paper leak concerns ',
 'Hundreds of cats stolen for food in Vietnam rescued by police, welfare group says',
 'Tehran selling deal with US as victory – but for Iranians it was necessity',
 'Three reasons ships are not going through the Strait of Hormuz yet',
 'German broadcaster removes TV intro after Elon Musk takes legal action',
 'Watch as Jackson hits post for Senegal against France',
 "Hungary's MPs block return of Orbán, limiting rule of PM to eight years",
 "Musk's SpaceX overtakes Amazon to become world's fifth most valuable firm",
 'Russian artist and Putin critic shot dead in Poland',
 'Group planned to attack White House UFC event using snipers and drones, FBI says',
 'Swedish man jailed for four years for coercing wife into sex with 120 men',
 'World Cup 2026',
 "'Daylight robbery but worth it' - what fans are spending on World Cup",
 "Record draws and Europe's slow start - is the World Cup lacking jeopardy?",
 'From dazzling winger to veteran who barely runs - the evolution of Messi',
 "Iran 'most oppressed' team at World Cup, head coach says",
 'More to explore',
 'Fragile quiet in Lebanon as US-Iran truce leaves unanswered questions',
 'A year on, six questions still haunt the Air India crash investigation',
 'What is Helium-3 and could we get it from the moon?',
 'Why I sold my business to my staff',
 "How is Australia's under-16 ban working out?",
 'Recovery of Ebola patients offers rare moments of joy at epicentre of outbreak',
 "What one country's experiment says about attempts to boost birth rates",
 "Woman left traumatised by swinging says website 'facilitated abuse'",
 'Most watched',
 "How Prince George will follow in his father's footsteps at Eton College",
 'Drones create the first-ever Fifa scoreboard in Seattle sky',
 'What did Trump do differently to Obama on Iran?',
 'Royal Family joined by thousands at Trooping the Colour',
 "Former porn star: 'I got death threats from IS'",
 'Also in news',
 "'Dancing girl's' bare torso restored in Indian textbook after backlash",
 "Somaliland opens Jerusalem embassy after Israel's recognition of its independence",
 'Watch: California wildfires rage near passing vehicles',
 'Williams sisters receive Wimbledon doubles wildcard',
 "South Korea's Starbucks to shut for staff history lesson after backlash",
 'China detains two leaders of influential underground church',
 'Venezuela signs deal with US energy giant to rebuild power grid',
 'Cuba tourism collapses as US pressure campaign bites',
 'Most read',
 'Russian warship fires warning shots near UK-registered yacht in Channel',
 'Three reasons ships are not going through the Strait of Hormuz yet',
 'Dozens walk out as Google boss Pichai addresses Stanford graduates',
 'Russian artist and Putin critic shot dead in Poland',
 "'Daylight robbery but worth it' - what fans are spending on World Cup",
 'Group planned to attack White House UFC event using snipers and drones, FBI says',
 'Prince George to attend Eton College from September',
 'German broadcaster removes TV intro after Elon Musk takes legal action',
 'Unclear if US-Iran agreement will provide respite to Lebanon',
 "Musk's SpaceX overtakes Amazon to become world's fifth most valuable firm",
 'Sport',
 'Watch as Jackson hits post for Senegal against France',
 "Tuchel's defensive gambles and what do they say about Alexander-Arnold?",
 'Meet the Iraq player set to make history for Pakistan',
 'Tunisia sack Lamouchi just one game into World Cup',
 "Women's T20 World Cup: Ireland slump to 57-5 against ruthless England",
 'Rew to make debut as Smith misses second Test',
 'Williams sisters to play together at Wimbledon',
 'The BBC is in multiple languages']

391. Find the title of the webpage. url = 'https://en.wikipedia.org/wiki/Python_(programming_language)'

In [160]:
url = 'https://en.wikipedia.org/wiki/Python_(programming_language)'
headers = {
    'User-Agent' : 'Mozzila/5.0'
}
res = requests.get(url,headers=headers)
soup = BeautifulSoup(res.content,'html.parser')
print(soup.find('title').text)

Python (programming language) - Wikipedia

392. Find all the links on the page and print their URLs. url = 'https://en.wikipedia.org/wiki/Python_(programming_language)'

In [170]:
res = requests.get(url,headers=headers)
soup = BeautifulSoup(res.content,'html.parser')
li = soup.find_all('a')
urls = []
for l in li : 
    if l.has_attr('href'):
        urls.append(l['href'])
urls

['#bodyContent',
 '/wiki/Main_Page',
 '/wiki/Wikipedia:Contents',
 '/wiki/Portal:Current_events',
 '/wiki/Special:Random',
 '/wiki/Wikipedia:About',
 '//en.wikipedia.org/wiki/Wikipedia:Contact_us',
 '/wiki/Help:Contents',
 '/wiki/Help:Introduction',
 '/wiki/Wikipedia:Community_portal',
 '/wiki/Special:RecentChanges',
 '/wiki/Wikipedia:File_upload_wizard',
 '/wiki/Special:SpecialPages',
 '/wiki/Main_Page',
 '/wiki/Special:Search',
 'https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en',
 '/w/index.php?title=Special:CreateAccount&returnto=Python+%28programming+language%29',
 '/w/index.php?title=Special:UserLogin&returnto=Python+%28programming+language%29',
 'https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en',
 '/w/index.php?title=Special:CreateAccount&returnto=Python+%28programming+language%29',
 '/w/index.php?title=Special:UserLogin&returnto=Python+%28programming+language%29',
 '#',
 '#History',
 '#Design_philosophy_and_features',
 '#Enhancement_Proposals',
 '#Syntax_and_semantics',
 '#Indentation',
 '#Statements_and_control_flow',
 '#Expressions',
 '#Typing',
 '#Arithmetic_operations',
 '#Function_syntax',
 '#Code_examples',
 '#Libraries',
 '#Development_environments',
 '#Implementations',
 '#Reference_implementation',
 '#Limitations_of_the_reference_implementation',
 '#Other_implementations',
 '#Unsupported_implementations',
 '#Transpilers_to_other_languages',
 '#Performance',
 '#Language_development',
 '#Naming',
 '#Languages_influenced_by_Python',
 '#See_also',
 '#Notes',
 '#References',
 '#Sources',
 '#Further_reading',
 '#External_links',
 'https://af.wikipedia.org/wiki/Python_(programmeertaal)',
 'https://als.wikipedia.org/wiki/Python_(Programmiersprache)',
 'https://an.wikipedia.org/wiki/Python',
 'https://ar.wikipedia.org/wiki/%D8%A8%D8%A7%D9%8A%D8%AB%D9%88%D9%86_(%D9%84%D8%BA%D8%A9_%D8%A8%D8%B1%D9%85%D8%AC%D8%A9)',
 'https://as.wikipedia.org/wiki/%E0%A6%AA%E0%A6%BE%E0%A6%87%E0%A6%A5%E0%A6%A8',
 'https://ast.wikipedia.org/wiki/Python',
 'https://az.wikipedia.org/wiki/Python_(proqramla%C5%9Fd%C4%B1rma_dili)',
 'https://azb.wikipedia.org/wiki/%D9%BE%D8%A7%DB%8C%D8%AA%D9%88%D9%86',
 'https://ban.wikipedia.org/wiki/Python',
 'https://be-tarask.wikipedia.org/wiki/Python',
 'https://be.wikipedia.org/wiki/Python_(%D0%BC%D0%BE%D0%B2%D0%B0_%D0%BF%D1%80%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%B0%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)',
 'https://bg.wikipedia.org/wiki/Python',
 'https://bh.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%87%E0%A4%A5%E0%A4%A8',
 'https://bn.wikipedia.org/wiki/%E0%A6%AA%E0%A6%BE%E0%A6%87%E0%A6%A5%E0%A6%A8_(%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A7%8B%E0%A6%97%E0%A7%8D%E0%A6%B0%E0%A6%BE%E0%A6%AE%E0%A6%BF%E0%A6%82_%E0%A6%AD%E0%A6%BE%E0%A6%B7%E0%A6%BE)',
 'https://br.wikipedia.org/wiki/Python_(lavar_programmi%C3%B1)',
 'https://bs.wikipedia.org/wiki/Python_(programski_jezik)',
 'https://bug.wikipedia.org/wiki/Python',
 'https://ca.wikipedia.org/wiki/Python',
 'https://ceb.wikipedia.org/wiki/Python_(programming_language)',
 'https://ckb.wikipedia.org/wiki/%D9%BE%D8%A7%DB%8C%D8%AA%DB%86%D9%86_(%D8%B2%D9%85%D8%A7%D9%86%DB%8C_%D8%A8%DB%95%D8%B1%D9%86%D8%A7%D9%85%DB%95%D8%B3%D8%A7%D8%B2%DB%8C)',
 'https://cs.wikipedia.org/wiki/Python',
 'https://cy.wikipedia.org/wiki/Python_(iaith_raglennu)',
 'https://da.wikipedia.org/wiki/Python_(programmeringssprog)',
 'https://de.wikipedia.org/wiki/Python_(Programmiersprache)',
 'https://dtp.wikipedia.org/wiki/Python_(boros_tokud)',
 'https://el.wikipedia.org/wiki/Python',
 'https://eo.wikipedia.org/wiki/Python_(programlingvo)',
 'https://es.wikipedia.org/wiki/Python',
 'https://et.wikipedia.org/wiki/Python_(programmeerimiskeel)',
 'https://eu.wikipedia.org/wiki/Python_(informatika)',
 'https://fa.wikipedia.org/wiki/%D9%BE%D8%A7%DB%8C%D8%AA%D9%88%D9%86_(%D8%B2%D8%A8%D8%A7%D9%86_%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3%DB%8C)',
 'https://fi.wikipedia.org/wiki/Python_(ohjelmointikieli)',
 'https://fj.wikipedia.org/wiki/Python',
 'https://fr.wikipedia.org/wiki/Python_(langage)',
 'https://gl.wikipedia.org/wiki/Python',
 'https://glk.wikipedia.org/wiki/%D9%BE%D8%A7%D9%8A%D8%AA%D8%A4%D9%86_(%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%8A%D9%88%D9%8A%D8%B3%D9%8A_%D8%B2%D9%88%D8%A7%D9%86)',
 'https://gu.wikipedia.org/wiki/%E0%AA%AA%E0%AA%BE%E0%AA%AF%E0%AA%A5%E0%AB%8B%E0%AA%A8_(%E0%AA%AA%E0%AB%8D%E0%AA%B0%E0%AB%8B%E0%AA%97%E0%AB%8D%E0%AA%B0%E0%AA%BE%E0%AA%AE%E0%AA%BF%E0%AA%82%E0%AA%97_%E0%AA%AD%E0%AA%BE%E0%AA%B7%E0%AA%BE)',
 'https://ha.wikipedia.org/wiki/Python_programming_language',
 'https://he.wikipedia.org/wiki/%D7%A4%D7%99%D7%99%D7%AA%D7%95%D7%9F',
 'https://hi.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%87%E0%A4%A5%E0%A4%A8',
 'https://hr.wikipedia.org/wiki/Python_(programski_jezik)',
 'https://hu.wikipedia.org/wiki/Python_(programoz%C3%A1si_nyelv)',
 'https://hy.wikipedia.org/wiki/Python',
 'https://ia.wikipedia.org/wiki/Python_(linguage_de_programmation)',
 'https://id.wikipedia.org/wiki/Python_(bahasa_pemrograman)',
 'https://io.wikipedia.org/wiki/Python',
 'https://is.wikipedia.org/wiki/Python_(forritunarm%C3%A1l)',
 'https://it.wikipedia.org/wiki/Python',
 'https://ja.wikipedia.org/wiki/Python',
 'https://jbo.wikipedia.org/wiki/paiton',
 'https://ka.wikipedia.org/wiki/%E1%83%9E%E1%83%90%E1%83%98%E1%83%97%E1%83%9D%E1%83%9C%E1%83%98_(%E1%83%9E%E1%83%A0%E1%83%9D%E1%83%92%E1%83%A0%E1%83%90%E1%83%9B%E1%83%98%E1%83%A0%E1%83%94%E1%83%91%E1%83%98%E1%83%A1_%E1%83%94%E1%83%9C%E1%83%90)',
 'https://kaa.wikipedia.org/wiki/Python_(programmalast%C4%B1r%C4%B1w_tili)',
 'https://kk.wikipedia.org/wiki/Python',
 'https://km.wikipedia.org/wiki/%E1%9E%95%E1%9E%B6%E1%9E%99%E1%9E%90%E1%9E%BB%E1%9E%93',
 'https://ko.wikipedia.org/wiki/%ED%8C%8C%EC%9D%B4%EC%8D%AC',
 'https://ku.wikipedia.org/wiki/Python_(ziman%C3%AA_bernamesaziy%C3%AA)',
 'https://ky.wikipedia.org/wiki/Python',
 'https://la.wikipedia.org/wiki/Python_(lingua_programmationis)',
 'https://lmo.wikipedia.org/wiki/Python',
 'https://lo.wikipedia.org/wiki/%E0%BB%84%E0%BA%9E%E0%BA%97%E0%BA%AD%E0%BA%99_(%E0%BA%9E%E0%BA%B2%E0%BA%AA%E0%BA%B2%E0%BB%82%E0%BA%9B%E0%BA%A3%E0%BB%81%E0%BA%81%E0%BA%A3%E0%BA%A1)',
 'https://lt.wikipedia.org/wiki/Python',
 'https://lv.wikipedia.org/wiki/Python_(programm%C4%93%C5%A1anas_valoda)',
 'https://mk.wikipedia.org/wiki/%D0%9F%D0%B0%D1%98%D1%82%D0%BE%D0%BD_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%81%D0%BA%D0%B8_%D1%98%D0%B0%D0%B7%D0%B8%D0%BA)',
 'https://ml.wikipedia.org/wiki/%E0%B4%AA%E0%B5%88%E0%B4%A4%E0%B5%8D%E0%B4%A4%E0%B5%BA_(%E0%B4%AA%E0%B5%8D%E0%B4%B0%E0%B5%8B%E0%B4%97%E0%B5%8D%E0%B4%B0%E0%B4%BE%E0%B4%AE%E0%B4%BF%E0%B4%99%E0%B5%8D%E0%B4%99%E0%B5%8D_%E0%B4%AD%E0%B4%BE%E0%B4%B7)',
 'https://mn.wikipedia.org/wiki/Python',
 'https://mr.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%AF%E0%A4%A5%E0%A4%A8_(%E0%A4%86%E0%A4%9C%E0%A5%8D%E0%A4%9E%E0%A4%BE%E0%A4%B5%E0%A4%B2%E0%A5%80_%E0%A4%AD%E0%A4%BE%E0%A4%B7%E0%A4%BE)',
 'https://ms.wikipedia.org/wiki/Python',
 'https://my.wikipedia.org/wiki/Python_(programming_language)',
 'https://nds.wikipedia.org/wiki/Python_(Programmeerspraak)',
 'https://ne.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%87%E0%A4%A5%E0%A4%A8_(%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A5%8B%E0%A4%97%E0%A4%BE%E0%A4%AE%E0%A4%BF%E0%A4%99_%E0%A4%AD%E0%A4%BE%E0%A4%B7%E0%A4%BE)',
 'https://nl.wikipedia.org/wiki/Python_(programmeertaal)',
 'https://nn.wikipedia.org/wiki/Python',
 'https://no.wikipedia.org/wiki/Python',
 'https://nqo.wikipedia.org/wiki/%DF%94%DF%8A%DF%8C%DF%95%DF%90%DF%B2%DF%AC',
 'https://olo.wikipedia.org/wiki/Python',
 'https://or.wikipedia.org/wiki/%E0%AC%AA%E0%AC%BE%E0%AC%87%E0%AC%A5%E0%AC%A8%E0%AD%8D_(%E0%AC%AA%E0%AD%8D%E0%AC%B0%E0%AD%8B%E0%AC%97%E0%AD%8D%E0%AC%B0%E0%AC%BE%E0%AC%AE%E0%AC%BF%E0%AC%82_%E0%AC%AD%E0%AC%BE%E0%AC%B7%E0%AC%BE)',
 'https://pa.wikipedia.org/wiki/%E0%A8%AA%E0%A8%BE%E0%A8%88%E0%A8%A5%E0%A8%A8_(%E0%A8%AA%E0%A9%8D%E0%A8%B0%E0%A9%8B%E0%A8%97%E0%A8%B0%E0%A8%BE%E0%A8%AE%E0%A8%BF%E0%A9%B0%E0%A8%97_%E0%A8%AD%E0%A8%BE%E0%A8%B8%E0%A8%BC%E0%A8%BE)',
 'https://pl.wikipedia.org/wiki/Python',
 'https://pms.wikipedia.org/wiki/Python_(lengagi_%C3%ABd_programassion)',
 'https://pnb.wikipedia.org/wiki/%D9%BE%D8%A7%D8%A6%DB%8C%D8%AA%DA%BE%D9%86_(%DA%A9%D9%85%D9%BE%DB%8C%D9%88%D9%B9%D8%B1_%D8%A8%D9%88%D9%84%DB%8C)',
 'https://pt.wikipedia.org/wiki/Python',
 'https://qu.wikipedia.org/wiki/Python',
 'https://ro.wikipedia.org/wiki/Python',
 'https://ru.wikipedia.org/wiki/Python',
 'https://sah.wikipedia.org/wiki/Python',
 'https://sat.wikipedia.org/wiki/%E1%B1%AF%E1%B1%9F%E1%B1%AD%E1%B1%9B%E1%B1%B7%E1%B1%9A%E1%B1%B1_(%E1%B1%AF%E1%B1%A8%E1%B1%B3%E1%B1%9C%E1%B1%BD%E1%B1%A8%E1%B1%9F%E1%B1%A2%E1%B1%A4%E1%B1%9D_%E1%B1%AF%E1%B1%9F%E1%B1%B9%E1%B1%A8%E1%B1%A5%E1%B1%A4)',
 'https://sco.wikipedia.org/wiki/Python_(programmin_leid)',
 'https://sh.wikipedia.org/wiki/Python_(programski_jezik)',
 'https://shn.wikipedia.org/wiki/Python_(programming_language)',
 'https://si.wikipedia.org/wiki/%E0%B6%B4%E0%B6%BA%E0%B7%92%E0%B6%AD%E0%B6%B1%E0%B7%8A',
 'https://simple.wikipedia.org/wiki/Python_(programming_language)',
 'https://sk.wikipedia.org/wiki/Python_(programovac%C3%AD_jazyk)',
 'https://sl.wikipedia.org/wiki/Python_(programski_jezik)',
 'https://sq.wikipedia.org/wiki/Python',
 'https://sr.wikipedia.org/wiki/Python_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%81%D0%BA%D0%B8_%D1%98%D0%B5%D0%B7%D0%B8%D0%BA)',
 'https://sv.wikipedia.org/wiki/Python_(programspr%C3%A5k)',
 'https://sw.wikipedia.org/wiki/Python_(lugha_ya_programu)',
 'https://ta.wikipedia.org/wiki/%E0%AE%AA%E0%AF%88%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AE%BE%E0%AE%A9%E0%AF%8D',
 'https://te.wikipedia.org/wiki/%E0%B0%AA%E0%B1%88%E0%B0%A5%E0%B0%BE%E0%B0%A8%E0%B1%8D_(%E0%B0%95%E0%B0%82%E0%B0%AA%E0%B1%8D%E0%B0%AF%E0%B1%82%E0%B0%9F%E0%B0%B0%E0%B1%8D_%E0%B0%AD%E0%B0%BE%E0%B0%B7)',
 'https://tg.wikipedia.org/wiki/Python',
 'https://th.wikipedia.org/wiki/%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%9E%E0%B8%97%E0%B8%AD%E0%B8%99',
 'https://tl.wikipedia.org/wiki/Python_(wikang_pamprograma)',
 'https://tok.wikipedia.org/wiki/toki_ilo_Pason',
 'https://tr.wikipedia.org/wiki/Python',
 'https://tt.wikipedia.org/wiki/Python',
 'https://ug.wikipedia.org/wiki/%D9%BE%D8%A7%D9%8A%D8%B3%D9%88%D9%86',
 'https://uk.wikipedia.org/wiki/Python',
 'https://ur.wikipedia.org/wiki/%D9%BE%D8%A7%D8%A6%DB%8C%D8%AA%DA%BE%D9%86_(%D9%BE%D8%B1%D9%88%DA%AF%D8%B1%D8%A7%D9%85%D9%86%DA%AF_%D8%B2%D8%A8%D8%A7%D9%86)',
 'https://uz.wikipedia.org/wiki/Python',
 'https://vi.wikipedia.org/wiki/Python_(ng%C3%B4n_ng%E1%BB%AF_l%E1%BA%ADp_tr%C3%ACnh)',
 'https://wa.wikipedia.org/wiki/Python_(lingaedje_%C3%A9ndjolike)',
 'https://war.wikipedia.org/wiki/Python_(programming_language)',
 'https://wuu.wikipedia.org/wiki/Python',
 'https://xmf.wikipedia.org/wiki/Python_(%E1%83%9E%E1%83%A0%E1%83%9D%E1%83%92%E1%83%A0%E1%83%90%E1%83%9B%E1%83%98%E1%83%A0%E1%83%90%E1%83%A4%E1%83%90%E1%83%A8_%E1%83%9C%E1%83%98%E1%83%9C%E1%83%90)',
 'https://zh-classical.wikipedia.org/wiki/%E8%9F%92%E8%AA%9E',
 'https://zh-min-nan.wikipedia.org/wiki/Python',
 'https://zh-yue.wikipedia.org/wiki/Python',
 'https://zh.wikipedia.org/wiki/Python',
 'https://www.wikidata.org/wiki/Special:EntityPage/Q28865#sitelinks-wikipedia',
 '/wiki/Python_(programming_language)',
 '/wiki/Talk:Python_(programming_language)',
 '/wiki/Python_(programming_language)',
 '/w/index.php?title=Python_(programming_language)&action=edit',
 '/w/index.php?title=Python_(programming_language)&action=history',
 '/wiki/Python_(programming_language)',
 '/w/index.php?title=Python_(programming_language)&action=edit',
 '/w/index.php?title=Python_(programming_language)&action=history',
 '/wiki/Special:WhatLinksHere/Python_(programming_language)',
 '/wiki/Special:RecentChangesLinked/Python_(programming_language)',
 '//en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard',
 '/w/index.php?title=Python_(programming_language)&oldid=1358757939',
 '/w/index.php?title=Python_(programming_language)&action=info',
 '/w/index.php?title=Special:CiteThisPage&page=Python_%28programming_language%29&id=1358757939&wpFormIdentifier=titleform',
 '/w/index.php?title=Special:UrlShortener&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPython_%28programming_language%29',
 '/w/index.php?title=Special:DownloadAsPdf&page=Python_%28programming_language%29&action=show-download-screen',
 '/w/index.php?title=Python_(programming_language)&printable=yes',
 'https://abstract.wikipedia.org/wiki/Q28865',
 'https://commons.wikimedia.org/wiki/Python_(programming_language)',
 'https://www.mediawiki.org/wiki/Python',
 'https://en.wikibooks.org/wiki/Python_Programming',
 'https://www.wikifunctions.org/wiki/Z610',
 'https://en.wikiquote.org/wiki/Python',
 'https://en.wikiversity.org/wiki/Python',
 'https://www.wikidata.org/wiki/Special:EntityPage/Q28865',
 '/wiki/File:Python-logo-notext.svg',
 '/wiki/Programming_paradigm',
 '/wiki/Multi-paradigm',
 '/wiki/Object-oriented_programming',
 '#cite_note-1',
 '/wiki/Procedural_programming',
 '/wiki/Imperative_programming',
 '/wiki/Functional_programming',
 '/wiki/Structured_programming',
 '/wiki/Reflective_programming',
 '/wiki/Software_design',
 '/wiki/Guido_van_Rossum',
 '/wiki/Software_developer',
 '/wiki/Python_Software_Foundation',
 '#cite_note-alt-sources-history-2',
 '/wiki/Software_release_life_cycle',
 '#cite_note-wikidata-a0eeb389e03a9833ed4781ad19ac2726a42a4ba1-v20-3',
 'https://www.wikidata.org/wiki/Q28865?uselang=en#P348',
 '/wiki/Type_system',
 '/wiki/Duck_typing',
 '/wiki/Dynamic_typing',
 '/wiki/Strong_and_weak_typing',
 '#cite_note-4',
 '/wiki/Optional_typing',
 '#cite_note-6',
 '/wiki/Memory_management',
 '/wiki/Garbage_collection_(computer_science)',
 '/wiki/Operating_system',
 '/wiki/Cross-platform',
 '#cite_note-12',
 '/wiki/Software_license',
 '/wiki/Python_Software_Foundation_License',
 '/wiki/Filename_extension',
 '#cite_note-venners-interview-pt-1-13',
 '#cite_note-pep488-14',
 '#cite_note-pep273-15',
 '#cite_note-pep561-16',
 '#cite_note-pep397-17',
 '#cite_note-pep0441-18',
 'https://www.python.org/',
 '/wiki/Programming_language_implementation',
 '/wiki/CPython',
 '/wiki/PyPy',
 '/wiki/MicroPython',
 '/wiki/CircuitPython',
 '/wiki/IronPython',
 '/wiki/Jython',
 '/wiki/Stackless_Python',
 '/wiki/Programming_language#Dialects,_flavors_and_implementations',
 '/wiki/Cython',
 '/wiki/RPython',
 '/wiki/Starlark',
 '#cite_note-19',
 '/wiki/ABC_(programming_language)',
 '#cite_note-faq-created-20',
 '/wiki/Ada_(programming_language)',
 '#cite_note-21',
 '/wiki/Wikipedia:Verifiability',
 '/wiki/ALGOL_68',
 '#cite_note-98-interview-22',
 '/wiki/APL_(programming_language)',
 '#cite_note-python.org-23',
 '/wiki/C_(programming_language)',
 '#cite_note-AutoNT-1-24',
 '/wiki/C%2B%2B',
 '#cite_note-classmix-25',
 '/wiki/CLU_(programming_language)',
 '#cite_note-effbot-call-by-object-26',
 '/wiki/Dylan_(programming_language)',
 '#cite_note-AutoNT-2-27',
 '/wiki/Haskell',
 '#cite_note-AutoNT-3-28',
 '#cite_note-python.org-23',
 '/wiki/Icon_(programming_language)',
 '#cite_note-AutoNT-4-29',
 '/wiki/Lisp_(programming_language)',
 '#cite_note-AutoNT-6-30',
 '/wiki/Modula-3',
 '#cite_note-98-interview-22',
 '#cite_note-classmix-25',
 '/wiki/Perl',
 '#cite_note-31',
 '/wiki/Standard_ML',
 '#cite_note-python.org-23',
 '/wiki/Apache_Groovy',
 '/wiki/Boo_(programming_language)',
 '/wiki/Cobra_(programming_language)',
 '/wiki/CoffeeScript',
 '#cite_note-32',
 '/wiki/D_(programming_language)',
 '/wiki/F_Sharp_(programming_language)',
 '/wiki/GDScript',
 '/wiki/Go_(programming_language)',
 '/wiki/JavaScript',
 '#cite_note-33',
 '#cite_note-34',
 '/wiki/Julia_(programming_language)',
 '#cite_note-Julia-35',
 '/wiki/Mojo_(programming_language)',
 '#cite_note-Mojo-36',
 '/wiki/Nim_(programming_language)',
 '/wiki/Ruby_(programming_language)',
 '#cite_note-bini-37',
 '/wiki/Swift_(programming_language)',
 '#cite_note-lattner2014-38',
 '/wiki/V_(programming_language)',
 '#cite_note-vpeople-39',
 '/wiki/File:Wikibooks-logo.svg',
 'https://en.wikibooks.org/wiki/Python_Programming',
 '/wiki/Category:Python_(programming_language)',
 '/wiki/Python_(programming_language)',
 '/wiki/List_of_Python_software#Web_frameworks',
 '/wiki/BlueBream',
 '/wiki/CherryPy',
 '/wiki/CubicWeb',
 '/wiki/Django_(web_framework)',
 '/wiki/FastAPI',
 '/wiki/Flask_(web_framework)',
 '/wiki/Google_App_Engine',
 '/wiki/Grok_(web_framework)',
 '/wiki/Kivy_(framework)',
 '/wiki/Mod_wsgi',
 '/wiki/Nevow',
 '/wiki/Pylons_(web_framework)',
 '/wiki/Pyramid_(web_framework)',
 '/wiki/Python_Paste',
 '/wiki/Quixote_(web_framework)',
 '/wiki/RapidSMS',
 '/wiki/Robot_Framework',
 '/wiki/Spyce_(software)',
 '/wiki/Tornado_(web_server)',
 '/wiki/TurboGears',
 '/wiki/Web2py',
 '/wiki/Zope_2',
 '#Libraries',
 '/wiki/AppJar',
 '/wiki/Anaconda_(Python_distribution)',
 '/wiki/Apache_MXNet',
 '/wiki/Apache_Singa',
 '/wiki/Astropy',
 '/wiki/Beautiful_Soup_(HTML_parser)',
 '/wiki/Biopython',
 '/wiki/Chainer',
 '/wiki/CatBoost',
 '/wiki/CheetahTemplate',
 '/wiki/Construct_(python_library)',
 '/wiki/Cubes_(OLAP_server)',
 '/wiki/CuPy',
 '/wiki/Dask_(software)',
 '/wiki/DEAP_(software)',
 '/wiki/DeepSpeed',
 '/wiki/Enthought',
 '/wiki/Genshi_(templating_language)',
 '/wiki/Gensim',
 '/wiki/Graph-tool',
 '/wiki/Horovod_(machine_learning)',
 '/wiki/Python_Imaging_Library',
 '/wiki/IPython',
 '/wiki/JAX_(software)',
 '/wiki/Jinja_(template_engine)',
 '/wiki/Keras',
 '/wiki/Manim',
 '/wiki/Matplotlib',
 '/wiki/Mako_(template_engine)',
 '/wiki/MindSpore',
 '/wiki/Mlpy',
 '/wiki/MNE-Python',
 '/wiki/Natural_Language_Toolkit',
 '/wiki/NetworkX',
 '/wiki/NeuroKit',
 '/wiki/NumPy',
 '/wiki/OceanParcels',
 '/wiki/Orange_(software)',
 '/wiki/Panda3D',
 '/wiki/Pandas_(software)',
 '/wiki/PlaidML',
 '/wiki/Plotly',
 '/wiki/ProbLog#Implementations',
 '/wiki/Pvlib_python',
 '/wiki/PyGObject',
 '/wiki/PyGTK',
 '/wiki/PyMC3',
 '/wiki/PyObjC',
 '/wiki/Pygame',
 '/wiki/PyQt',
 '/wiki/Python_Robotics',
 '/wiki/PySide',
 '/wiki/PyTorch',
 '/wiki/PyTorch_Lightning',
 '/wiki/Python-Ogre',
 '/wiki/Qiskit',
 '/wiki/QLattice',
 '/wiki/RDKit',
 '/wiki/RPyC',
 '/wiki/Sage_Manifolds',
 '/wiki/SageMath',
 '/wiki/ScientificPython',
 '/wiki/Scikit-learn',
 '/wiki/Scikit-multiflow',
 '/wiki/SciPy',
 '/wiki/SimpleITK',
 '/wiki/SpaCy',
 '/wiki/Sphinx_(documentation_generator)',
 '/wiki/SQLAlchemy',
 '/wiki/SQLObject',
 '/wiki/Storm_(software)',
 '/wiki/SymPy',
 '/wiki/TensorFlow',
 '/wiki/Theano_(software)',
 '/wiki/Tkinter',
 '/wiki/Twisted_(software)',
 '/wiki/TomoPy',
 '/wiki/Hugging_Face#Transformers_Library',
 '/wiki/Veusz',
 '/wiki/VPython',
 '/wiki/WxPython',
 '/wiki/XDMF',
 '/wiki/Comparison_of_integrated_development_environments#Python',
 '/wiki/Atom_(text_editor)',
 '/wiki/Atom_(text_editor)#History',
 '/wiki/Codelobster',
 '/wiki/EasyEclipse',
 '/wiki/Eclipse_(software)',
 '/wiki/Emacs',
 '/wiki/Eric_Python_IDE',
 '/wiki/Geany',
 '/wiki/Google_Colab',
 '/wiki/IDLE',
 '/wiki/Jupyter_notebook',
 '/wiki/Kaggle_Notebooks',
 '/wiki/Komodo_IDE',
 '/wiki/NetBeans',
 '/wiki/PyCharm',
 '/wiki/PythonAnywhere',
 '/wiki/Python_Tools_for_Visual_Studio',
 '/wiki/Replit',
 '/wiki/Spyder_(software)',
 '/wiki/Thonny',
 '/wiki/Vim_(text_editor)',
 '/wiki/Visual_Studio_Code',
 '/wiki/Wing_IDE',
 '#Implementations',
 '/wiki/ActivePython',
 '/wiki/CLPython',
 '/wiki/CPython',
 '/wiki/Cython',
 '/wiki/Intel_Distribution_for_Python',
 '/wiki/IronPython',
 '/wiki/Jython',
 '/wiki/MicroPython',
 '/wiki/Nuitka',
 '/wiki/Numba',
 '/wiki/Parrot_virtual_machine',
 '/wiki/Psyco',
 '/wiki/PyPy',
 '/wiki/Pyrex_(programming_language)',
 '/wiki/Python_for_S60',
 '/wiki/Shed_Skin',
 '/wiki/Stackless_Python',
 '/wiki/Unladen_Swallow',
 '/wiki/History_of_Python',
 '/wiki/List_of_computer_books#Python',
 '/wiki/Outline_of_the_Python_programming_language#Python_conferences',
 '/wiki/List_of_Python_software',
 '/wiki/List_of_unit_testing_frameworks#Python',
 '/wiki/Outline_of_the_Python_programming_language',

393. Find the first paragraph on the page and print its text.

In [172]:
res = requests.get(url,headers=headers)
soup = BeautifulSoup(res.content,'html.parser')
p = soup.find('p')
p.text

'\n'

394. Find all the headings on the page and print their text.

In [177]:
res = requests.get(url,headers=headers)
soup = BeautifulSoup(res.content,'html.parser')
h = soup.find_all(['h1','h2','h3','h4','h5','h6'])
for i in h : 
    print(i.text)

Contents
Python (programming language)
History
Design philosophy and features
Enhancement Proposals
Syntax and semantics
Indentation
Statements and control flow
Expressions
Typing
Arithmetic operations
Function syntax
Code examples
Libraries
Development environments
Implementations
Reference implementation
Limitations of the reference implementation
Other implementations
Unsupported implementations
Transpilers to other languages
Performance
Language development
Naming
Languages influenced by Python
See also
Notes
References
Sources
Further reading
External links

395. Find the table on the page and its rows, Extract the data from each row, and print it url =
'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population'

In [196]:
url = 'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population'
res = requests.get(url,headers=headers)
soup = BeautifulSoup(res.content,'html.parser')
table = soup.find('table',class_='wikitable')
data = []
row = table.find_all('tr')
for r in row :
    cols = r.find_all(['th','td'])
    cols = [col.text.strip() for col in cols]
    data.append(cols)
df = pd.DataFrame(data[1:],columns=data[0])
df

,Location,Population,% ofworld,Date,Source (official or fromthe United Nations),Notes
0,World,"8,232,000,000",100%,13 Jun 2025,UN projection[1][3],
1,India,"1,417,492,000",17.2%,1 Jul 2025,Official projection[4],[b]
2,China,"1,404,890,000",17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,"341,784,857",4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,"288,315,089",3.5%,31 Dec 2025,National annual projection[7],
...,...,...,...,...,...,...
235,Christmas Island (Australia),"1,692",0%,1 Jan 2021,2021 Census[248],
236,Niue (New Zealand),"1,681",0%,11 Nov 2022,2022 Census[249],
237,Vatican City,882,0%,31 Dec 2024,Official figure[250],[ah]
238,Cocos (Keeling) Islands (Australia),593,0%,30 Jun 2020,2021 Census[251],
239,Pitcairn Islands (UK),35,0%,1 Jul 2023,Official estimate[252],

In [211]:
with open('Scrape_this.html','r',encoding='utf-8') as f :
    res = f.read()
soup = BeautifulSoup(res,'html.parser')
data = {
    "Company_Name": [],
    "Company_Link": [],
    "Current_Price": [],
    "Value": [],
    "Volume": []
}
table = soup.find('table',class_='common-table')
rows = table.find_all('tr')[1:]
for row in rows : 
    cols = row.find_all('td')
    if len(cols)>0 :
        company = cols[0].find('a')
        data["Company_Name"].append(company.text.strip())
        data["Company_Link"].append(company["href"])
        data["Current_Price"].append(cols[1].text.strip())
        data["Value"].append(cols[5].text.strip())
        data["Volume"].append(cols[6].text.strip())

df = pd.DataFrame(data)
df

,Company_Name,Company_Link,Current_Price,Value,Volume
0,Vodafone Idea,https://www.ndtv.com/business/stock/vodafone-i...,7.75,35.47,"45,763.00"
1,Reliance Power,https://www.ndtv.com/business/stock/reliance-p...,15.01,31.44,"20,947.33"
2,Yes Bank,https://www.ndtv.com/business/stock/yes-bank-l...,16.21,16.25,"10,026.87"
3,NHPC,https://www.ndtv.com/business/stock/nhpc-ltd_nhpc,45.80,23.52,"5,136.20"
4,IDFC First Bank,https://www.ndtv.com/business/stock/idfc-first...,82.17,38.62,"4,699.80"
...,...,...,...,...,...
190,MRF,https://www.ndtv.com/business/stock/mrf-ltd_mrf,100429.90,4.73,0.47
191,P&G Hygiene,https://www.ndtv.com/business/stock/procter-ga...,13961.40,0.52,0.37
192,3M India,https://www.ndtv.com/business/stock/3m-india-l...,27181.25,0.82,0.30
193,Abbott India,https://www.ndtv.com/business/stock/abbott-ind...,22685.05,0.64,0.28
194,Bajaj Hold & Invest,https://www.ndtv.com/business/stock/bajaj-hold...,7005.10,0.16,0.23

# 406

In [239]:
with open('Popular_Quotes.html','r',encoding='utf-8') as f :
    res = f.read()
soup = BeautifulSoup(res,'html.parser')
df = {
    'quotes' : [],
    'author' : [],
    'likes' : []
}
for i in (soup.find_all('div',class_='quote')):
    df['quotes'].append(i.find('div',class_='quoteText').text.strip().split("―")[0])
    df['author'].append(i.find('div',class_='quoteText').text.strip().split("―")[1].split('\n')[2])
    df['likes'].append(i.find('a',class_='smallText').text.split(' ')[0])
df1 = pd.DataFrame(df)
df1

,quotes,author,likes
0,“Be yourself; everyone else is already taken.”...,Oscar Wilde,172090
1,"“I'm selfish, impatient and a little insecure....",Marilyn Monroe,162993
2,"“So many books, so little time.”\n \n",Frank Zappa,147069
3,“Two things are infinite: the universe and hum...,Albert Einstein,146082
4,“A room without books is like a body without a...,Marcus Tullius Cicero,133363
5,"“Be who you are and say what you feel, because...",Bernard M. Baruch,128599
6,“You've gotta dance like there's nobody watchi...,William W. Purkey,127116
7,“You know you're in love when you can't fall a...,Dr. Seuss,124987
8,"“You only live once, but if you do it right, o...",Mae West,117240
9,“Be the change that you wish to see in the wor...,Mahatma Gandhi,113213
10,“In three words I can sum up everything I've l...,Robert Frost,108002
11,"“If you want to know what a man's like, take a...","J.K. Rowling,",100983
12,“Don’t walk in front of me… I may not followDo...,Albert Camus,92274
13,"“If you tell the truth, you don't have to reme...",Mark Twain,90869
14,“Friendship ... is born at the moment when one...,"C.S. Lewis,",87553
15,“I've learned that people will forget what you...,Maya Angelou,87398
16,“A friend is someone who knows all about you a...,Elbert Hubbard,83514
17,“To live is the rarest thing in the world. Mos...,Oscar Wilde,83168
18,“Always forgive your enemies; nothing annoys t...,Oscar Wilde,80923
19,“Darkness cannot drive out darkness: only ligh...,"Martin Luther King Jr.,",77451
20,“Live as if you were to die tomorrow. Learn as...,Mahatma Gandhi,77061
21,“We accept the love we think we deserve.”\n ...,"Stephen Chbosky,",74875
22,"“Without music, life would be a mistake.”\n ...","Friedrich Nietzsche,",73251
23,“I am so clever that sometimes I don't underst...,"Oscar Wilde,",71126
24,“To be yourself in a world that is constantly ...,Ralph Waldo Emerson,69009
25,“Here's to the crazy ones. The misfits. The re...,Steve Jobs,67728
26,"“Insanity is doing the same thing, over and ov...",Narcotics Anonymous,64173
27,“I believe that everything happens for a reaso...,Marilyn Monroe,61795
28,“It is better to be hated for what you are tha...,"Andre Gide,",61028
29,“Twenty years from now you will be more disapp...,"H. Jackson Brown Jr.,",59792

407. From the given Popular_Quotes.html, load the file ensuring the utf-8 encoding and do the following task using BeautifulSoup
library in python.
1.Extract the text from the 'h1' tag and display it.
2.Retrieve the text of the <Ɵtle> tag, then display it in reverse order.
3.What is the total number of <script> tags in the HTML?
4.Extract all tags listed under the first quote by Oscar Wilde and print the tag with the most characters.
5.Print the first 5 quotes along with their authors in the below given format:
Example:
Quote: “Be yourself; everyone else is already taken.”
Author: Oscar Wilde
6.Display the quotes that contain the word "accomplishment" in its text.
7.Extract the number of likes for each quote and display them in ascending order.
8.Find and print the names of authors who have more than one quote on the page.
9.Create a DataFrame containing the quote, author name, and number of likes.

In [292]:
with open('Popular_Quotes.html','r',encoding='utf-8') as f:
    res = f.read()
soup = BeautifulSoup(res,'html.parser')
h1 = soup.find_all('h1')[0]
print(h1.text)
t = soup.find_all('title')[0].text.strip()
print(t[::-1])
s = soup.find_all('script')
print(len(s))
tag = soup.find('div',class_='quote')
max_tag = ''
max_len = 0
for t in tag.find_all('a') : 
    tt = t.text.strip()
    if len(tt) > max_len : 
        max_len = len(tt)
        max_tag = tt
print(f"{max_tag} {max_len}")


for i in soup.find_all('div','quote')[:5] :
    q = i.find('div',class_='quoteText').text.strip().split('―')[0]
    a = i.find('div',class_='quoteText').text.strip().split('―')[1].strip()
    print(f"Quote : {q}")
    print(f"Author : {a}")

print("Display the quotes that contain the word accomplishment in its text")
for i in soup.find_all('div','quote') :
    q = i.find('div',class_='quoteText').text.strip().split('―')[0]
    if 'accomplishment' in q.lower() :
        print(q)

likes = []
for i in soup.find_all('div','quote') : 
    likes.append(int(i.find('a',class_='smallText').text.strip().split(' ')[0]))
likes.sort()
print(likes)

print("More then 1 author ")
authors = {}
for i in soup.find_all('div','quote'):
    a = i.find('div',class_='quoteText').text.strip().split('―')[1].strip()
    if a in authors : 
        authors[a] +=1
    else : 
        authors[a] = 1
for author,count in authors.items():
    if count>1 :
        print(author)

Popular quotes
setouQ ralupoP
28
misattributed-oscar-wilde 25
Quote : “Be yourself; everyone else is already taken.”


Author : Oscar Wilde
Quote : “I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.”


Author : Marilyn Monroe
Quote : “So many books, so little time.”


Author : Frank Zappa
Quote : “Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”


Author : Albert Einstein
Quote : “A room without books is like a body without a soul.”


Author : Marcus Tullius Cicero
Display the quotes that contain the word accomplishment in its text
“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”


[59792, 61028, 61795, 64173, 67728, 69009, 71126, 73251, 74875, 77061, 77451, 80923, 83168, 83514, 87398, 87553, 90869, 92274, 100983, 108002, 113213, 117240, 124987, 127116, 128599, 133363, 146082, 147069, 162993, 172090]
More then 1 author
Oscar Wilde
Marilyn Monroe
Mahatma Gandhi

403. For the given web page “Certified used Mercedes-Benz for sale.html” scrape the dataof car Name, Mileage, Dealer name,Review
Count and Price.
Create Dataframe for that.

In [325]:
with open('Certified used Mercedes-Benz for sale.html','r',encoding='utf-8') as f :
    res = f.read()
soup = BeautifulSoup(res,'html.parser')
df = {
    'name' : [],
    'mileage' : [],
    'dealer' : [],
    'review' : [],
    'price' : []
}

for i in soup.find_all('div',class_='vehicle-card') :
    df['name'].append(i.find('h2',class_='title').text)
    df['mileage'].append(i.find('div',class_='mileage').text)
    df['dealer'].append(i.find('div',class_='dealer-name').text.strip())
    df['review'].append(i.find('span',class_='sds-rating__link sds-button-link').text.split('reviews')[0].split('(')[1])
    df['price'].append(i.find('span',class_='primary-price').text)
df = pd.DataFrame(df)
df

,name,mileage,dealer,review,price
0,2020 Mercedes-Benz CLA 250 Base 4MATIC,"28,744 mi.",Mercedes-Benz of Lynnwood,130,"$35,995"
1,2019 Mercedes-Benz AMG GT 53 Base,"25,771 mi.",International Autos,117,"$79,995"
2,2021 Mercedes-Benz AMG GLE 53 Base,"22,374 mi.",John Sisson Motors,38,"$80,923"
3,2022 Mercedes-Benz AMG CLA 45 Base 4MATIC,"10,595 mi.",Mercedes-Benz of Santa Rosa,30,"$56,633"
4,2021 Mercedes-Benz AMG GLE 53 Base,"33,622 mi.",Mercedes-Benz of Rochester,152,"$76,995"
5,2021 Mercedes-Benz E-Class E 450 4MATIC,"12,477 mi.",Benzel-Busch Motor Car,"5,283","$76,532"
6,2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC,"22,383 mi.",Mercedes-Benz of Lancaster,174,"$102,990"
7,2019 Mercedes-Benz S-Class S 560,"49,332 mi.",Mercedes-Benz of Ontario,"2,016","$54,580"
8,2021 Mercedes-Benz AMG GLE 53 Base,"37,688 mi.",John Sisson Motors,38,"$76,715"
9,2021 Mercedes-Benz GLA 250 Base,"19,521 mi.",Mercedes-Benz of Augusta,264,"$34,999"
10,2022 Mercedes-Benz AMG C 43 Base 4MATIC,"14,420 mi.",Mercedes-Benz of Chicago,"1,327","$62,991"
11,2018 Mercedes-Benz AMG C 43 Base 4MATIC,"34,555 mi.",Mercedes-Benz of South Orlando,"1,388","$39,999"
12,2021 Mercedes-Benz E-Class E 450 4MATIC,"16,474 mi.",Contemporary Motor Cars Inc.,226,"$74,998"
13,2021 Mercedes-Benz S-Class S 580 4MATIC,"10,233 mi.",Mercedes-Benz of Fort Washington,"2,788","$99,822"
14,2022 Mercedes-Benz GLE 450 AWD 4MATIC,"6,800 mi.",Mercedes-Benz of Chicago,"1,327","$73,990"
15,2018 Mercedes-Benz GLC 300 Base 4MATIC,"54,467 mi.",Mercedes-Benz of Fort Washington,"2,788","$29,151"
16,2022 Mercedes-Benz AMG GLA 35 Base,"8,690 mi.",Mercedes-Benz of Fort Washington,"2,788","$49,736"
17,2022 Mercedes-Benz GLB 250 Base,"8,158 mi.",Mercedes-Benz Of Tampa,"3,521","$42,000"
18,2022 Mercedes-Benz S-Class S 500 4MATIC,"8,401 mi.",Mercedes-Benz of Walnut Creek,"1,016","$86,986"
19,2020 Mercedes-Benz AMG S 63 Base 4MATIC,"24,958 mi.",Autobahn Motors,"1,000","$105,997"
20,2021 Mercedes-Benz GLC 300 Base 4MATIC,"49,278 mi.",Bergstrom Luxury on Victory Lane,292,"$37,280"